# Double Encoding Double Classification (2E2C) - 4A and 6B experiments

In [1]:
import os
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# load the predictions of xgb from 4A
os.chdir("C:/Users/Cristina/OneDrive/Documenti/BCG/Tesi/Test_patients")
test_4A = pd.read_csv('Test_patients_predicted_values_xgb_4A.txt', sep=None, engine='python')
test_4A

                    Patient  Target  Predicted value
0    brca_smc_2018_BB01_130       0                0
1    brca_smc_2018_BB01_110       1                1
2    brca_smc_2018_BB01_037       1                1
3    brca_smc_2018_BB01_126       1                1
4       brca_smc_2018_BR097       1                0
..                      ...     ...              ...
139     MBCProject_27uAugT4       0                1
140     MBCProject_2kS5fYc1       0                0
141     MBCProject_7oIotZSe       0                0
142     MBCProject_LVSjf8h7       0                0
143     MBCProject_pktAIxFb       0                0

[144 rows x 3 columns]

In [3]:
tcga_patients_test_4A = test_4A[test_4A['Patient'].str.startswith('TCGA')]
tcga_patients_test_4A

          Patient  Target  Predicted value
16   TCGA-A2-A04P       1                1
17   TCGA-A2-A0D0       1                1
18   TCGA-A2-A0T2       1                1
19   TCGA-A2-A0YE       1                1
20   TCGA-A2-A1G1       1                1
..            ...     ...              ...
127  TCGA-E9-A1RE       0                0
128  TCGA-EW-A1PD       0                0
129  TCGA-GM-A2DN       0                0
130  TCGA-OL-A5D8       0                0
131  TCGA-OL-A5RU       0                0

[79 rows x 3 columns]

In [4]:
(tcga_patients_test_4A['Target'] == tcga_patients_test_4A['Predicted value']).sum()

68

In [5]:
(test_4A['Target'] == test_4A['Predicted value']).sum()

120

In [6]:
# load the predictions of polynomial SVM from 6B
test_6B = pd.read_csv('Test_patients_predicted_values_svm_poly.txt', sep=None, engine='python')
test_6B

                   Patient  Target  Predicted value
0   brca_smc_2018_BB01_037       1                1
1   brca_smc_2018_BB01_110       1                1
2   brca_smc_2018_BB01_126       1                1
3                 BR-M-045       1                1
4                  PD4133a       1                1
..                     ...     ...              ...
68     MBCProject_pktAIxFb       0                0
69     brca_smc_2018_BR331       0                0
70                X01BR015       0                1
71            TCGA-AN-A0XS       0                0
72                 MBC_159       0                0

[73 rows x 3 columns]

In [7]:
tcga_patients_test_6B = test_6B[test_6B['Patient'].str.startswith('TCGA')]
tcga_patients_test_6B

         Patient  Target  Predicted value
7   TCGA-A2-A0D0       1                1
8   TCGA-AC-A6IW       1                1
9   TCGA-AN-A0AL       1                1
10  TCGA-AO-A129       1                1
11  TCGA-AR-A0TP       1                1
12  TCGA-AR-A1AJ       1                1
13  TCGA-B6-A0I1       1                1
14  TCGA-B6-A409       1                1
15  TCGA-BH-A0E0       1                1
16  TCGA-C8-A131       1                0
17  TCGA-C8-A1HJ       1                1
18  TCGA-C8-A27B       1                1
19  TCGA-D8-A142       1                1
20  TCGA-D8-A27F       1                1
21  TCGA-E2-A14R       1                1
22  TCGA-E2-A14Y       1                0
23  TCGA-E9-A1N8       1                1
24  TCGA-E9-A244       1                1
25  TCGA-OL-A5S0       1                0
42  TCGA-A1-A0SI       0                0
43  TCGA-A2-A0CL       0                1
44  TCGA-A2-A0EQ       0                0
45  TCGA-A2-A0YH       0                0
46  TCGA-A2-A0YI       0                0
47  TCGA-A7-A0DB       0                0
48  TCGA-A8-A093       0                0
49  TCGA-AC-A23E       0                0
50  TCGA-AO-A03L       0                0
51  TCGA-AO-A03M       0                0
52  TCGA-AO-A0J2       0                1
53  TCGA-AR-A1AV       0                0
54  TCGA-AR-A24S       0                0
55  TCGA-B6-A0X5       0                0
56  TCGA-B6-A401       0                0
57  TCGA-BH-A0BJ       0                0
58  TCGA-BH-A0BO       0                0
59  TCGA-BH-A0H3       0                0
60  TCGA-BH-A1FU       0                1
61  TCGA-D8-A1JJ       0                0
62  TCGA-D8-A27K       0                0
63  TCGA-E9-A1R0       0                0
71  TCGA-AN-A0XS       0                0

In [8]:
tcga_patients_test_6B.shape

(42, 3)

In [9]:
(tcga_patients_test_6B['Target'] == tcga_patients_test_6B['Predicted value']).sum()

36

In [10]:
# Count the number of patients where Target equals Predicted
count_matches_6B = (test_6B['Target'] == test_6B['Predicted value']).sum()
count_matches_6B

60

In [11]:
test_pts_6B_list = test_6B['Patient'].to_list()
test_pts_6B_list

['brca_smc_2018_BB01_037',
 'brca_smc_2018_BB01_110',
 'brca_smc_2018_BB01_126',
 'BR-M-045',
 'PD4133a',
 'X18BR002',
 'X20BR008',
 'TCGA-A2-A0D0',
 'TCGA-AC-A6IW',
 'TCGA-AN-A0AL',
 'TCGA-AO-A129',
 'TCGA-AR-A0TP',
 'TCGA-AR-A1AJ',
 'TCGA-B6-A0I1',
 'TCGA-B6-A409',
 'TCGA-BH-A0E0',
 'TCGA-C8-A131',
 'TCGA-C8-A1HJ',
 'TCGA-C8-A27B',
 'TCGA-D8-A142',
 'TCGA-D8-A27F',
 'TCGA-E2-A14R',
 'TCGA-E2-A14Y',
 'TCGA-E9-A1N8',
 'TCGA-E9-A244',
 'TCGA-OL-A5S0',
 'MBC_163',
 'MBC_167',
 'MBC_10',
 'MBC_31',
 'MBC_33',
 'MBC_60',
 'MBC_182',
 'MBC_204',
 'MBCProject_d5CbUNTb',
 'MBCProject_oqupfDu7',
 'brca_smc_2018_BB01_017',
 'brca_smc_2018_BB01_130',
 'brca_smc_2018_BR371',
 'X11BR011',
 'X11BR014',
 'X21BR002',
 'TCGA-A1-A0SI',
 'TCGA-A2-A0CL',
 'TCGA-A2-A0EQ',
 'TCGA-A2-A0YH',
 'TCGA-A2-A0YI',
 'TCGA-A7-A0DB',
 'TCGA-A8-A093',
 'TCGA-AC-A23E',
 'TCGA-AO-A03L',
 'TCGA-AO-A03M',
 'TCGA-AO-A0J2',
 'TCGA-AR-A1AV',
 'TCGA-AR-A24S',
 'TCGA-B6-A0X5',
 'TCGA-B6-A401',
 'TCGA-BH-A0BJ',
 'TCGA-BH-A0BO',
 'TCGA-BH-A0H3',
 'TCGA-BH-A1FU',
 'TCGA-D8-A1JJ',
 'TCGA-D8-A27K',
 'TCGA-E9-A1R0',
 'MBC_128',
 'MBC_72',
 'MBC_183',
 'MBC_199',
 'MBCProject_pktAIxFb',
 'brca_smc_2018_BR331',
 'X01BR015',
 'TCGA-AN-A0XS',
 'MBC_159']

In [12]:
test_4A_selected = test_4A[test_4A['Patient'].isin(test_pts_6B_list)]
test_4A_selected

                    Patient  Target  Predicted value
0    brca_smc_2018_BB01_130       0                0
1    brca_smc_2018_BB01_110       1                1
2    brca_smc_2018_BB01_037       1                1
3    brca_smc_2018_BB01_126       1                1
9                  BR-M-045       1                1
..                      ...     ...              ...
134                 MBC_159       0                0
136                  MBC_72       0                0
137                 MBC_183       0                0
138                 MBC_199       0                0
143     MBCProject_pktAIxFb       0                0

[73 rows x 3 columns]

In [13]:
# Count the number of patients where Target equals Predicted
count_matches_4A_selected = (test_4A_selected['Target'] == test_4A_selected['Predicted value']).sum()
count_matches_4A_selected

59

### Merge the two datasets

In [14]:
test_4A_selected = test_4A_selected.rename(columns = {'Predicted value':'Predicted_4A_xgb'})
test_4A_selected

                    Patient  Target  Predicted_4A_xgb
0    brca_smc_2018_BB01_130       0                 0
1    brca_smc_2018_BB01_110       1                 1
2    brca_smc_2018_BB01_037       1                 1
3    brca_smc_2018_BB01_126       1                 1
9                  BR-M-045       1                 1
..                      ...     ...               ...
134                 MBC_159       0                 0
136                  MBC_72       0                 0
137                 MBC_183       0                 0
138                 MBC_199       0                 0
143     MBCProject_pktAIxFb       0                 0

[73 rows x 3 columns]

In [15]:
test_6B = test_6B.rename(columns = {'Predicted value':'Predicted_6B_svm_poly'})
test_6B

                   Patient  Target  Predicted_6B_svm_poly
0   brca_smc_2018_BB01_037       1                      1
1   brca_smc_2018_BB01_110       1                      1
2   brca_smc_2018_BB01_126       1                      1
3                 BR-M-045       1                      1
4                  PD4133a       1                      1
..                     ...     ...                    ...
68     MBCProject_pktAIxFb       0                      0
69     brca_smc_2018_BR331       0                      0
70                X01BR015       0                      1
71            TCGA-AN-A0XS       0                      0
72                 MBC_159       0                      0

[73 rows x 3 columns]

In [16]:
test_6B_noTarget = test_6B.drop('Target', axis=1)
test_6B_noTarget

                   Patient  Predicted_6B_svm_poly
0   brca_smc_2018_BB01_037                      1
1   brca_smc_2018_BB01_110                      1
2   brca_smc_2018_BB01_126                      1
3                 BR-M-045                      1
4                  PD4133a                      1
..                     ...                    ...
68     MBCProject_pktAIxFb                      0
69     brca_smc_2018_BR331                      0
70                X01BR015                      1
71            TCGA-AN-A0XS                      0
72                 MBC_159                      0

[73 rows x 2 columns]

In [17]:
# merge the two dataframes 
test_4Aand6B = pd.merge(test_4A_selected, test_6B_noTarget, how='inner', on=['Patient'])
test_4Aand6B

                   Patient  Target  Predicted_4A_xgb  Predicted_6B_svm_poly
0   brca_smc_2018_BB01_130       0                 0                      0
1   brca_smc_2018_BB01_110       1                 1                      1
2   brca_smc_2018_BB01_037       1                 1                      1
3   brca_smc_2018_BB01_126       1                 1                      1
4                 BR-M-045       1                 1                      1
..                     ...     ...               ...                    ...
68                 MBC_159       0                 0                      0
69                  MBC_72       0                 0                      0
70                 MBC_183       0                 0                      0
71                 MBC_199       0                 0                      0
72     MBCProject_pktAIxFb       0                 0                      0

[73 rows x 4 columns]

In [18]:
# count for how many patients the predicted values from the 2 models are equal
count_matches_4Aand6B_predictions = (test_4Aand6B['Predicted_4A_xgb'] == test_4Aand6B['Predicted_6B_svm_poly']).sum()
count_matches_4Aand6B_predictions

66

In [19]:
matching_pts_4Aand6B_predictions = test_4Aand6B[test_4Aand6B['Predicted_4A_xgb'] == test_4Aand6B['Predicted_6B_svm_poly']]
matching_pts_4Aand6B_predictions

                   Patient  Target  Predicted_4A_xgb  Predicted_6B_svm_poly
0   brca_smc_2018_BB01_130       0                 0                      0
1   brca_smc_2018_BB01_110       1                 1                      1
2   brca_smc_2018_BB01_037       1                 1                      1
3   brca_smc_2018_BB01_126       1                 1                      1
4                 BR-M-045       1                 1                      1
..                     ...     ...               ...                    ...
68                 MBC_159       0                 0                      0
69                  MBC_72       0                 0                      0
70                 MBC_183       0                 0                      0
71                 MBC_199       0                 0                      0
72     MBCProject_pktAIxFb       0                 0                      0

[66 rows x 4 columns]

In [20]:
NONmatching_pts_4Aand6B_predictions = test_4Aand6B[test_4Aand6B['Predicted_4A_xgb'] != test_4Aand6B['Predicted_6B_svm_poly']]
NONmatching_pts_4Aand6B_predictions

         Patient  Target  Predicted_4A_xgb  Predicted_6B_svm_poly
6       X18BR002       1                 1                      0
40      X01BR015       0                 0                      1
44  TCGA-A1-A0SI       0                 1                      0
46  TCGA-A2-A0EQ       0                 1                      0
53  TCGA-AO-A03L       0                 1                      0
57  TCGA-AR-A24S       0                 1                      0
63  TCGA-BH-A1FU       0                 0                      1

In [21]:
# count for how many patients the predicted values from the 2 models and the true value are equal 
count_matches_4Aand6B_predictions = (
    (test_4Aand6B['Predicted_4A_xgb'] == test_4Aand6B['Predicted_6B_svm_poly']) & 
    (test_4Aand6B['Predicted_6B_svm_poly'] == test_4Aand6B['Target'])
).sum()

count_matches_4Aand6B_predictions

56

In [22]:
matching_pts_4Aand6B_CORRECTpredictions = test_4Aand6B[
    (test_4Aand6B['Predicted_4A_xgb'] == test_4Aand6B['Predicted_6B_svm_poly']) & 
    (test_4Aand6B['Predicted_6B_svm_poly'] == test_4Aand6B['Target'])]
matching_pts_4Aand6B_CORRECTpredictions

                   Patient  Target  Predicted_4A_xgb  Predicted_6B_svm_poly
0   brca_smc_2018_BB01_130       0                 0                      0
1   brca_smc_2018_BB01_110       1                 1                      1
2   brca_smc_2018_BB01_037       1                 1                      1
3   brca_smc_2018_BB01_126       1                 1                      1
4                 BR-M-045       1                 1                      1
5                  PD4133a       1                 1                      1
8             TCGA-A2-A0D0       1                 1                      1
9             TCGA-AC-A6IW       1                 1                      1
10            TCGA-AN-A0AL       1                 1                      1
11            TCGA-AO-A129       1                 1                      1
12            TCGA-AR-A0TP       1                 1                      1
13            TCGA-AR-A1AJ       1                 1                      1
14            TCGA-B6-A0I1       1                 1                      1
15            TCGA-B6-A409       1                 1                      1
16            TCGA-BH-A0E0       1                 1                      1
18            TCGA-C8-A1HJ       1                 1                      1
19            TCGA-C8-A27B       1                 1                      1
20            TCGA-D8-A142       1                 1                      1
21            TCGA-D8-A27F       1                 1                      1
22            TCGA-E2-A14R       1                 1                      1
24            TCGA-E9-A1N8       1                 1                      1
25            TCGA-E9-A244       1                 1                      1
27                 MBC_163       1                 1                      1
28                 MBC_167       1                 1                      1
29                  MBC_10       1                 1                      1
31                  MBC_33       1                 1                      1
32                  MBC_60       1                 1                      1
33                 MBC_182       1                 1                      1
34                 MBC_204       1                 1                      1
35     MBCProject_d5CbUNTb       1                 1                      1
38     brca_smc_2018_BR331       0                 0                      0
39     brca_smc_2018_BR371       0                 0                      0
42                X11BR014       0                 0                      0
43                X21BR002       0                 0                      0
47            TCGA-A2-A0YH       0                 0                      0
48            TCGA-A2-A0YI       0                 0                      0
49            TCGA-A7-A0DB       0                 0                      0
50            TCGA-A8-A093       0                 0                      0
51            TCGA-AC-A23E       0                 0                      0
52            TCGA-AN-A0XS       0                 0                      0
54            TCGA-AO-A03M       0                 0                      0
56            TCGA-AR-A1AV       0                 0                      0
58            TCGA-B6-A0X5       0                 0                      0
59            TCGA-B6-A401       0                 0                      0
60            TCGA-BH-A0BJ       0                 0                      0
61            TCGA-BH-A0BO       0                 0                      0
62            TCGA-BH-A0H3       0                 0                      0
64            TCGA-D8-A1JJ       0                 0                      0
65            TCGA-D8-A27K       0                 0                      0
66            TCGA-E9-A1R0       0                 0                      0
67                 MBC_128       0                 0                      0
68                 MBC_159       0                 0                      0
69                  MBC_72       0                 0                      0
70                 MBC_183       0                 0                      0
71                 MBC_199       0                 0                      0
72     MBCProject_pktAIxFb       0                 0                      0

In [23]:
matching_pts_4Aand6B_CORRECTpredictions.shape

(56, 4)

In [24]:
matching_pts_4Aand6B_CORRECTpredictions_list = matching_pts_4Aand6B_CORRECTpredictions['Patient'].to_list()
matching_pts_4Aand6B_CORRECTpredictions_list

['brca_smc_2018_BB01_130',
 'brca_smc_2018_BB01_110',
 'brca_smc_2018_BB01_037',
 'brca_smc_2018_BB01_126',
 'BR-M-045',
 'PD4133a',
 'TCGA-A2-A0D0',
 'TCGA-AC-A6IW',
 'TCGA-AN-A0AL',
 'TCGA-AO-A129',
 'TCGA-AR-A0TP',
 'TCGA-AR-A1AJ',
 'TCGA-B6-A0I1',
 'TCGA-B6-A409',
 'TCGA-BH-A0E0',
 'TCGA-C8-A1HJ',
 'TCGA-C8-A27B',
 'TCGA-D8-A142',
 'TCGA-D8-A27F',
 'TCGA-E2-A14R',
 'TCGA-E9-A1N8',
 'TCGA-E9-A244',
 'MBC_163',
 'MBC_167',
 'MBC_10',
 'MBC_33',
 'MBC_60',
 'MBC_182',
 'MBC_204',
 'MBCProject_d5CbUNTb',
 'brca_smc_2018_BR331',
 'brca_smc_2018_BR371',
 'X11BR014',
 'X21BR002',
 'TCGA-A2-A0YH',
 'TCGA-A2-A0YI',
 'TCGA-A7-A0DB',
 'TCGA-A8-A093',
 'TCGA-AC-A23E',
 'TCGA-AN-A0XS',
 'TCGA-AO-A03M',
 'TCGA-AR-A1AV',
 'TCGA-B6-A0X5',
 'TCGA-B6-A401',
 'TCGA-BH-A0BJ',
 'TCGA-BH-A0BO',
 'TCGA-BH-A0H3',
 'TCGA-D8-A1JJ',
 'TCGA-D8-A27K',
 'TCGA-E9-A1R0',
 'MBC_128',
 'MBC_159',
 'MBC_72',
 'MBC_183',
 'MBC_199',
 'MBCProject_pktAIxFb']

In [25]:
# common uncorrect predictions
matching_pts_4Aand6B_predictions[~matching_pts_4Aand6B_predictions['Patient'].isin(matching_pts_4Aand6B_CORRECTpredictions_list)]

                   Patient  Target  Predicted_4A_xgb  Predicted_6B_svm_poly
7                 X20BR008       1                 0                      0
17            TCGA-C8-A131       1                 0                      0
23            TCGA-E2-A14Y       1                 0                      0
26            TCGA-OL-A5S0       1                 0                      0
30                  MBC_31       1                 0                      0
36     MBCProject_oqupfDu7       1                 0                      0
37  brca_smc_2018_BB01_017       0                 1                      1
41                X11BR011       0                 1                      1
45            TCGA-A2-A0CL       0                 1                      1
55            TCGA-AO-A0J2       0                 1                      1

### How does the total performance on the 4A test set improve if we consider the performance of 6B on the 73 patients of the 6B test set?

In [26]:
test_4A

                    Patient  Target  Predicted value
0    brca_smc_2018_BB01_130       0                0
1    brca_smc_2018_BB01_110       1                1
2    brca_smc_2018_BB01_037       1                1
3    brca_smc_2018_BB01_126       1                1
4       brca_smc_2018_BR097       1                0
..                      ...     ...              ...
139     MBCProject_27uAugT4       0                1
140     MBCProject_2kS5fYc1       0                0
141     MBCProject_7oIotZSe       0                0
142     MBCProject_LVSjf8h7       0                0
143     MBCProject_pktAIxFb       0                0

[144 rows x 3 columns]

In [27]:
test_6B

                   Patient  Target  Predicted_6B_svm_poly
0   brca_smc_2018_BB01_037       1                      1
1   brca_smc_2018_BB01_110       1                      1
2   brca_smc_2018_BB01_126       1                      1
3                 BR-M-045       1                      1
4                  PD4133a       1                      1
..                     ...     ...                    ...
68     MBCProject_pktAIxFb       0                      0
69     brca_smc_2018_BR331       0                      0
70                X01BR015       0                      1
71            TCGA-AN-A0XS       0                      0
72                 MBC_159       0                      0

[73 rows x 3 columns]

In [28]:
test_6B_2 = test_6B.rename(columns = {'Predicted_6B_svm_poly':'Predicted value'})
test_6B_2

                   Patient  Target  Predicted value
0   brca_smc_2018_BB01_037       1                1
1   brca_smc_2018_BB01_110       1                1
2   brca_smc_2018_BB01_126       1                1
3                 BR-M-045       1                1
4                  PD4133a       1                1
..                     ...     ...              ...
68     MBCProject_pktAIxFb       0                0
69     brca_smc_2018_BR331       0                0
70                X01BR015       0                1
71            TCGA-AN-A0XS       0                0
72                 MBC_159       0                0

[73 rows x 3 columns]

In [29]:
# consider the 4A test set excluding the test patients of 6B
test_4A_MINUS6B = test_4A[~test_4A['Patient'].isin(test_pts_6B_list)]
test_4A_MINUS6B

                 Patient  Target  Predicted value
4    brca_smc_2018_BR097       1                0
5    brca_smc_2018_BR105       1                1
6    brca_smc_2018_BR145       1                1
7    brca_smc_2018_BR301       1                1
8    brca_smc_2018_BR419       1                1
..                   ...     ...              ...
135              MBC_178       0                0
139  MBCProject_27uAugT4       0                1
140  MBCProject_2kS5fYc1       0                0
141  MBCProject_7oIotZSe       0                0
142  MBCProject_LVSjf8h7       0                0

[71 rows x 3 columns]

In [30]:
(test_4A_MINUS6B['Target'] == test_4A_MINUS6B['Predicted value']).sum()

61

In [31]:
# concatenate test_4A_MINUS6B and test_6B
test_set_6Band4A = pd.concat([test_6B_2, test_4A_MINUS6B], axis=0)
test_set_6Band4A

                    Patient  Target  Predicted value
0    brca_smc_2018_BB01_037       1                1
1    brca_smc_2018_BB01_110       1                1
2    brca_smc_2018_BB01_126       1                1
3                  BR-M-045       1                1
4                   PD4133a       1                1
..                      ...     ...              ...
135                 MBC_178       0                0
139     MBCProject_27uAugT4       0                1
140     MBCProject_2kS5fYc1       0                0
141     MBCProject_7oIotZSe       0                0
142     MBCProject_LVSjf8h7       0                0

[144 rows x 3 columns]

### Evaluate the performance of the test set obtained through Double Encoding Double Classification (2E2C)      approach

In [32]:
y_test_df = test_set_6Band4A[['Patient', 'Target']]
y_test_df

                    Patient  Target
0    brca_smc_2018_BB01_037       1
1    brca_smc_2018_BB01_110       1
2    brca_smc_2018_BB01_126       1
3                  BR-M-045       1
4                   PD4133a       1
..                      ...     ...
135                 MBC_178       0
139     MBCProject_27uAugT4       0
140     MBCProject_2kS5fYc1       0
141     MBCProject_7oIotZSe       0
142     MBCProject_LVSjf8h7       0

[144 rows x 2 columns]

In [33]:
y_test_df.set_index('Patient', inplace=True)
y_test_df

                        Target
Patient
brca_smc_2018_BB01_037       1
brca_smc_2018_BB01_110       1
brca_smc_2018_BB01_126       1
BR-M-045                     1
PD4133a                      1
...                        ...
MBC_178                      0
MBCProject_27uAugT4          0
MBCProject_2kS5fYc1          0
MBCProject_7oIotZSe          0
MBCProject_LVSjf8h7          0

[144 rows x 1 columns]

In [34]:
y_test_df.index.name = None
y_test_df

                        Target
brca_smc_2018_BB01_037       1
brca_smc_2018_BB01_110       1
brca_smc_2018_BB01_126       1
BR-M-045                     1
PD4133a                      1
...                        ...
MBC_178                      0
MBCProject_27uAugT4          0
MBCProject_2kS5fYc1          0
MBCProject_7oIotZSe          0
MBCProject_LVSjf8h7          0

[144 rows x 1 columns]

In [35]:
y_test_df.value_counts()

Target
0         72
1         72
Name: count, dtype: int64

In [36]:
y_test = y_test_df['Target']
y_test

brca_smc_2018_BB01_037    1
brca_smc_2018_BB01_110    1
brca_smc_2018_BB01_126    1
BR-M-045                  1
PD4133a                   1
                         ..
MBC_178                   0
MBCProject_27uAugT4       0
MBCProject_2kS5fYc1       0
MBCProject_7oIotZSe       0
MBCProject_LVSjf8h7       0
Name: Target, Length: 144, dtype: int64

In [37]:
test_set_6Band4A

                    Patient  Target  Predicted value
0    brca_smc_2018_BB01_037       1                1
1    brca_smc_2018_BB01_110       1                1
2    brca_smc_2018_BB01_126       1                1
3                  BR-M-045       1                1
4                   PD4133a       1                1
..                      ...     ...              ...
135                 MBC_178       0                0
139     MBCProject_27uAugT4       0                1
140     MBCProject_2kS5fYc1       0                0
141     MBCProject_7oIotZSe       0                0
142     MBCProject_LVSjf8h7       0                0

[144 rows x 3 columns]

In [38]:
# convert the 'Predicted value' column into an array
y_pred = test_set_6Band4A['Predicted value'].to_numpy()
y_pred

array([1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [39]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.86      0.84        72
           1       0.86      0.82      0.84        72

    accuracy                           0.84       144
   macro avg       0.84      0.84      0.84       144
weighted avg       0.84      0.84      0.84       144

In [40]:
# Test accuracy 
accuracy = np.mean(y_test == y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.8402777777777778

In [41]:
# build the confusion matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm)

[[62 10]
 [13 59]]

In [42]:
# precision: TP/(TP+FP) accuracy of the positive prediction
def precision(cm):
    TP = cm[1,1]
    TPFP = cm[:,1].sum()
    return TP / TPFP

In [43]:
print("Precision ", precision(cm))

Precision  0.855072463768116

In [44]:
# Recall:  TP/(TP+FN) ratio of positive instances correctly detected by the classifier
def recall(cm):
    TP = cm[1,1]
    T = cm[1,:].sum()
    return TP / T

In [45]:
print("Recall:", recall(cm))

Recall: 0.8194444444444444

In [46]:
# F1 score: 2 * precision_RF * recall_RF / (precision_RF + recall_RF)
def f1(cm):
    p = precision(cm)
    r = recall(cm)
    return (2 * p * r) / (p + r)

In [47]:
print("F1:", f1(cm))

F1: 0.8368794326241135

In [48]:
# MCC (Matthews correlation coefficient)

def mcc(y_true, y_pred):
    tp = np.sum(np.logical_and(y_true == 1, y_pred == 1))
    tn = np.sum(np.logical_and(y_true == 0, y_pred == 0))
    fp = np.sum(np.logical_and(y_true == 0, y_pred == 1))
    fn = np.sum(np.logical_and(y_true == 1, y_pred == 0))
    
    numerator = (tp * tn) - (fp * fn)
    denominator = np.sqrt((tp + fp) * (tp + fn) * (tn + fp) * (tn + fn))
    
    mcc_value = numerator / denominator
    return mcc_value

In [49]:
tp = np.sum(np.logical_and(y_test == 1, y_pred == 1))
tp

59

In [50]:
tn = np.sum(np.logical_and(y_test == 0, y_pred == 0))
tn

62

In [51]:
fp = np.sum(np.logical_and(y_test == 0, y_pred == 1))
fp

10

In [52]:
fn = np.sum(np.logical_and(y_test == 1, y_pred == 0))
fn

13

In [53]:
print("MCC:", mcc(y_test, y_pred))

MCC: 0.6811470859197776