## MutClustSW dataset preparation - Total patients (TNBC + non-TNBC)

18 hypermutated patients and 9 hypomutated patients are deleted

### 1. p-value < 0.05

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import os
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# load the total ductal mutation dataset with the corrected protein_positions end and start
os.chdir("C:/Users/Cristina/OneDrive/Documenti/BCG/Tesi/MutClust_considerVariantClassification")
total_ductal_dataset = pd.read_csv('data_mutation_total_ductal_without_hyper_CORRECTION_protein_pos.csv', sep=None, engine='python')
total_ductal_dataset

,PATIENT_ID,Tumor_Sample_Barcode,Hugo_Symbol,Chromosome,Start_Position,End_Position,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Transcript_ID,Gene_length,ENSP,Hugo_variant,Mutation_length,Protein_position_start,Protein_position_end
0,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,KALRN,3,123988087.0,123988087.0,Missense_Mutation,SNP,G,G,C,ENST00000240874.3:c.948G>C,p.E316D,ENST00000240874,646303,NaN,KALRN_Missense_Mutation,1.0,316.0,316.0
1,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,ANK2,4,114195720.0,114195720.0,Missense_Mutation,SNP,C,C,T,ENST00000357077.4:c.1598C>T,p.P533L,ENST00000357077,565632,NaN,ANK2_Missense_Mutation,1.0,533.0,533.0
2,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,SORBS2,4,186539742.0,186539742.0,Missense_Mutation,SNP,G,G,C,ENST00000355634.5:c.2936C>G,p.S979C,ENST00000355634,371209,NaN,SORBS2_Missense_Mutation,1.0,979.0,979.0
3,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,PCDHA11,5,140250828.0,140250828.0,Missense_Mutation,SNP,C,C,G,ENST00000398640.2:c.2140C>G,p.L714V,ENST00000398640,143241,NaN,PCDHA11_Missense_Mutation,1.0,714.0,714.0
4,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,WRNIP1,6,2766210.0,2766210.0,Missense_Mutation,SNP,C,C,A,ENST00000380773.4:c.354C>A,p.S118R,ENST00000380773,21539,NaN,WRNIP1_Missense_Mutation,1.0,118.0,118.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182216,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,NRSN2,20,333991.0,333991.0,Silent,SNP,C,C,T,ENST00000382285.2:c.327C>T,p.N109=,ENST00000382285,12879,NaN,NRSN2_Silent,1.0,109.0,109.0
182217,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,CHRNA4,20,61986887.0,61986887.0,Intron,SNP,G,G,C,ENST00000370263.4:c.383+440C>G,p.*128*,ENST00000370263,34334,NaN,CHRNA4_Intron,1.0,NaN,NaN
182218,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,CHRNA4,20,61987386.0,61987386.0,Silent,SNP,G,G,A,ENST00000370263.4:c.324C>T,p.V108=,ENST00000370263,34334,NaN,CHRNA4_Silent,1.0,108.0,108.0
182219,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,KCNQ2,20,62078103.0,62078103.0,Silent,SNP,G,G,A,ENST00000359125.2:c.384C>T,p.I128=,ENST00000359125,66452,NaN,KCNQ2_Silent,1.0,128.0,128.0
182220,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,XBP1,22,29191563.0,29191563.0,Nonsense_Mutation,SNP,G,G,A,ENST00000216037.6:c.757C>T,p.Q253*,ENST00000216037,6043,NaN,XBP1_Nonsense_Mutation,1.0,253.0,253.0

In [3]:
total_ductal_dataset['Hugo_Symbol'] = total_ductal_dataset['Hugo_Symbol'].replace(['EPPIN-WFDC6'], ['EPPIN'])

In [4]:
total_ductal_dataset['Hugo_Symbol'] = total_ductal_dataset['Hugo_Symbol'].replace(['EIF3CL'], ['EIF3C'])

In [5]:
# load the hypomutated and hypermutated patients 
os.chdir("C:/Users/Cristina/OneDrive/Documenti/BCG/Tesi")
hyper_hypo_patients_total_ductal = pd.read_csv('hyper_hypo_patients_total_ductal.csv', sep=',', engine='python')
hyper_hypo_patients_total_ductal

             PATIENT_ID
0          TCGA-BH-A18V
1          TCGA-A2-A0EV
2          TCGA-AC-A8OP
3              X01BR043
4          TCGA-A8-A08L
5          TCGA-AN-A046
6          TCGA-AC-A23H
7          TCGA-LL-A8F5
8   MBCProject_99CdCOHm
9          TCGA-BH-A18G
10         TCGA-AN-A0AK
11         TCGA-D8-A1XK
12         TCGA-BH-A0HF
13             X18BR003
14              MBC_189
15         TCGA-AO-A128
16         TCGA-D8-A1XQ
17         TCGA-D8-A1JA
18               MBC_21
19  brca_smc_2018_BR033
20              MBC_116
21         TCGA-EW-A1P1
22              MBC_149
23  brca_smc_2018_BR099
24              MBC_166
25              MBC_160
26               MBC_27

In [6]:
hyper_hypo_patients_total_ductal.shape

(27, 1)

### Delete all the rows associated to the hypermutated and hypomutated patients

In [7]:
mask_totalductal = total_ductal_dataset['PATIENT_ID'].isin(hyper_hypo_patients_total_ductal['PATIENT_ID'])
mask_totalductal

0         False
1         False
2         False
3         False
4         False
          ...
182216    False
182217    False
182218    False
182219    False
182220    False
Name: PATIENT_ID, Length: 182221, dtype: bool

In [8]:
data_mutation_total_ductal_nohypo_nohyper = total_ductal_dataset[~mask_totalductal]
data_mutation_total_ductal_nohypo_nohyper

,PATIENT_ID,Tumor_Sample_Barcode,Hugo_Symbol,Chromosome,Start_Position,End_Position,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Transcript_ID,Gene_length,ENSP,Hugo_variant,Mutation_length,Protein_position_start,Protein_position_end
0,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,KALRN,3,123988087.0,123988087.0,Missense_Mutation,SNP,G,G,C,ENST00000240874.3:c.948G>C,p.E316D,ENST00000240874,646303,NaN,KALRN_Missense_Mutation,1.0,316.0,316.0
1,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,ANK2,4,114195720.0,114195720.0,Missense_Mutation,SNP,C,C,T,ENST00000357077.4:c.1598C>T,p.P533L,ENST00000357077,565632,NaN,ANK2_Missense_Mutation,1.0,533.0,533.0
2,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,SORBS2,4,186539742.0,186539742.0,Missense_Mutation,SNP,G,G,C,ENST00000355634.5:c.2936C>G,p.S979C,ENST00000355634,371209,NaN,SORBS2_Missense_Mutation,1.0,979.0,979.0
3,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,PCDHA11,5,140250828.0,140250828.0,Missense_Mutation,SNP,C,C,G,ENST00000398640.2:c.2140C>G,p.L714V,ENST00000398640,143241,NaN,PCDHA11_Missense_Mutation,1.0,714.0,714.0
4,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,WRNIP1,6,2766210.0,2766210.0,Missense_Mutation,SNP,C,C,A,ENST00000380773.4:c.354C>A,p.S118R,ENST00000380773,21539,NaN,WRNIP1_Missense_Mutation,1.0,118.0,118.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182216,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,NRSN2,20,333991.0,333991.0,Silent,SNP,C,C,T,ENST00000382285.2:c.327C>T,p.N109=,ENST00000382285,12879,NaN,NRSN2_Silent,1.0,109.0,109.0
182217,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,CHRNA4,20,61986887.0,61986887.0,Intron,SNP,G,G,C,ENST00000370263.4:c.383+440C>G,p.*128*,ENST00000370263,34334,NaN,CHRNA4_Intron,1.0,NaN,NaN
182218,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,CHRNA4,20,61987386.0,61987386.0,Silent,SNP,G,G,A,ENST00000370263.4:c.324C>T,p.V108=,ENST00000370263,34334,NaN,CHRNA4_Silent,1.0,108.0,108.0
182219,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,KCNQ2,20,62078103.0,62078103.0,Silent,SNP,G,G,A,ENST00000359125.2:c.384C>T,p.I128=,ENST00000359125,66452,NaN,KCNQ2_Silent,1.0,128.0,128.0
182220,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,XBP1,22,29191563.0,29191563.0,Nonsense_Mutation,SNP,G,G,A,ENST00000216037.6:c.757C>T,p.Q253*,ENST00000216037,6043,NaN,XBP1_Nonsense_Mutation,1.0,253.0,253.0

In [9]:
data_mutation_total_ductal_nohypo_nohyper.PATIENT_ID.nunique()

1527

In [10]:
data_mutation_total_ductal_nohypo_nohyper.Hugo_Symbol.nunique()

19466

In [11]:
# save this dataset 
os.chdir("C:/Users/Cristina/OneDrive/Documenti/BCG/Tesi")
data_mutation_total_ductal_nohypo_nohyper.to_csv("data_mutation_total_ductal_nohypo_nohyper_CORRECTION_protein_pos_definitivo.csv", index=False, sep='\t')

In [12]:
data_mutation_total_ductal_nohypo_nohyper

,PATIENT_ID,Tumor_Sample_Barcode,Hugo_Symbol,Chromosome,Start_Position,End_Position,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Transcript_ID,Gene_length,ENSP,Hugo_variant,Mutation_length,Protein_position_start,Protein_position_end
0,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,KALRN,3,123988087.0,123988087.0,Missense_Mutation,SNP,G,G,C,ENST00000240874.3:c.948G>C,p.E316D,ENST00000240874,646303,NaN,KALRN_Missense_Mutation,1.0,316.0,316.0
1,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,ANK2,4,114195720.0,114195720.0,Missense_Mutation,SNP,C,C,T,ENST00000357077.4:c.1598C>T,p.P533L,ENST00000357077,565632,NaN,ANK2_Missense_Mutation,1.0,533.0,533.0
2,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,SORBS2,4,186539742.0,186539742.0,Missense_Mutation,SNP,G,G,C,ENST00000355634.5:c.2936C>G,p.S979C,ENST00000355634,371209,NaN,SORBS2_Missense_Mutation,1.0,979.0,979.0
3,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,PCDHA11,5,140250828.0,140250828.0,Missense_Mutation,SNP,C,C,G,ENST00000398640.2:c.2140C>G,p.L714V,ENST00000398640,143241,NaN,PCDHA11_Missense_Mutation,1.0,714.0,714.0
4,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,WRNIP1,6,2766210.0,2766210.0,Missense_Mutation,SNP,C,C,A,ENST00000380773.4:c.354C>A,p.S118R,ENST00000380773,21539,NaN,WRNIP1_Missense_Mutation,1.0,118.0,118.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182216,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,NRSN2,20,333991.0,333991.0,Silent,SNP,C,C,T,ENST00000382285.2:c.327C>T,p.N109=,ENST00000382285,12879,NaN,NRSN2_Silent,1.0,109.0,109.0
182217,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,CHRNA4,20,61986887.0,61986887.0,Intron,SNP,G,G,C,ENST00000370263.4:c.383+440C>G,p.*128*,ENST00000370263,34334,NaN,CHRNA4_Intron,1.0,NaN,NaN
182218,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,CHRNA4,20,61987386.0,61987386.0,Silent,SNP,G,G,A,ENST00000370263.4:c.324C>T,p.V108=,ENST00000370263,34334,NaN,CHRNA4_Silent,1.0,108.0,108.0
182219,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,KCNQ2,20,62078103.0,62078103.0,Silent,SNP,G,G,A,ENST00000359125.2:c.384C>T,p.I128=,ENST00000359125,66452,NaN,KCNQ2_Silent,1.0,128.0,128.0
182220,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,XBP1,22,29191563.0,29191563.0,Nonsense_Mutation,SNP,G,G,A,ENST00000216037.6:c.757C>T,p.Q253*,ENST00000216037,6043,NaN,XBP1_Nonsense_Mutation,1.0,253.0,253.0

In [13]:
# extract from the total ductal dataframe the unique Hugo Symbol genes 
unique_genes_total_ductal=data_mutation_total_ductal_nohypo_nohyper['Hugo_Symbol'].unique()
unique_genes_total_ductal=pd.DataFrame(unique_genes_total_ductal, columns=['Hugo_Symbol'])
unique_genes_total_ductal

         Hugo_Symbol
0              KALRN
1               ANK2
2             SORBS2
3            PCDHA11
4             WRNIP1
...              ...
19461          FGF17
19462          LYVE1
19463       C12orf29
19464          HSBP1
19465  MEF2BNB-MEF2B

[19466 rows x 1 columns]

In [14]:
# load the significant genes (TN + non TN) with p-val < 0.05
os.chdir("C:/Users/Cristina/OneDrive/Documenti/BCG/Tesi/Significant genes_definitivo")
significant_genes_TNandNONTN_pval_005 = pd.read_csv('significant_genes_totalTNandNONTN_pval_005_definitivo.csv', sep=',', engine='python')
significant_genes_TNandNONTN_pval_005

     Hugo_Symbol
0           TP53
1            RB1
2         PIK3CA
3          FBXW7
4           PTEN
...          ...
1012       TM2D1
1013       TRAF6
1014     HSPBAP1
1015      FERMT2
1016         TTN

[1017 rows x 1 columns]

In [15]:
significant_genes_TNandNONTN_pval_005['Hugo_Symbol'] = significant_genes_TNandNONTN_pval_005['Hugo_Symbol'].replace('EPPIN-WFDC6', 'EPPIN')

In [16]:
significant_genes_TNandNONTN_pval_005['Hugo_Symbol']  = significant_genes_TNandNONTN_pval_005['Hugo_Symbol'].replace(['EIF3CL'], ['EIF3C'])

In [17]:
# study if there are gene names inconsistencies between relevant genes with p-val < 0.05 and total ductal genes 
pd.merge(significant_genes_TNandNONTN_pval_005, unique_genes_total_ductal, how='inner', on=['Hugo_Symbol'])

     Hugo_Symbol
0           TP53
1            RB1
2         PIK3CA
3          FBXW7
4           PTEN
...          ...
1012       TM2D1
1013       TRAF6
1014     HSPBAP1
1015      FERMT2
1016         TTN

[1017 rows x 1 columns]

There are not gene names' inconsistencies

In [18]:
significant_genes_TNandNONTN_pval_005_array = significant_genes_TNandNONTN_pval_005['Hugo_Symbol'].values
significant_genes_TNandNONTN_pval_005_array

array(['TP53', 'RB1', 'PIK3CA', ..., 'HSPBAP1', 'FERMT2', 'TTN'],
      dtype=object)

### Preparation of the dataset for MutClust

In [19]:
# select the total ductal mutations belonging to the relevant genes found by MutSig (p-value < 0.05)
data_mutation_SINIFICANTgenes_bothTNandNONTN_p_005= data_mutation_total_ductal_nohypo_nohyper[data_mutation_total_ductal_nohypo_nohyper['Hugo_Symbol'].isin(significant_genes_TNandNONTN_pval_005_array)]
data_mutation_SINIFICANTgenes_bothTNandNONTN_p_005

,PATIENT_ID,Tumor_Sample_Barcode,Hugo_Symbol,Chromosome,Start_Position,End_Position,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Transcript_ID,Gene_length,ENSP,Hugo_variant,Mutation_length,Protein_position_start,Protein_position_end
15,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,TP53,17,7574003.0,7574003.0,Nonsense_Mutation,SNP,G,G,A,ENST00000269305.4:c.1024C>T,p.R342*,ENST00000269305,25760,NaN,TP53_Nonsense_Mutation,1.0,342.0,342.0
18,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,PIK3CA,3,178952150.0,178952151.0,Frame_Shift_Ins,INS,-,-,TTTT,ENST00000263967.3:c.3205_3206insTTTT,p.*1069Ffs*5,ENST00000263967,91980,NaN,PIK3CA_Frame_Shift_Ins,2.0,1069.0,1069.0
22,brca_smc_2018_BB01_004,brca_smc_2018_BB01_004,TP53,17,7577117.0,7577117.0,Missense_Mutation,SNP,A,A,C,ENST00000269305.4:c.821T>G,p.V274G,ENST00000269305,25760,NaN,TP53_Missense_Mutation,1.0,274.0,274.0
25,brca_smc_2018_BB01_004,brca_smc_2018_BB01_004,MAML3,4,140811082.0,140811083.0,In_Frame_Ins,INS,-,-,TGT,ENST00000509479.2:c.1508_1509insCAA,p.Q503delinsHK,ENST00000509479,437432,NaN,MAML3_In_Frame_Ins,2.0,503.0,503.0
26,brca_smc_2018_BB01_005,brca_smc_2018_BB01_005,SF3B4,1,149895518.0,149895518.0,Missense_Mutation,SNP,C,C,A,ENST00000271628.8:c.1191G>T,p.Q397H,ENST00000271628,5028,NaN,SF3B4_Missense_Mutation,1.0,397.0,397.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182145,MBCProject_ygcMFgCR,RP-1156_MBCProject_ygcMFgCR_T1A_v1_Exome,SOGA2,18,8824961.0,8824961.0,Silent,SNP,C,C,G,ENST00000306329.11:c.4410C>G,p.P1470=,ENST00000306329,127118,NaN,SOGA2_Silent,1.0,1470.0,1470.0
182163,MBCProject_ygcMFgCR,RP-1156_MBCProject_ygcMFgCR_T1A_v1_Exome,GATA3,10,8111513.0,8111514.0,Frame_Shift_Ins,INS,-,-,G,ENST00000346208.3:c.1003dup,p.D335Gfs*17,ENST00000346208,21595,NaN,GATA3_Frame_Shift_Ins,2.0,333.0,333.0
182168,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,EPAS1,2,46525087.0,46525087.0,Intron,SNP,G,G,A,ENST00000263734.3:c.26+11G>A,p.*9*,ENST00000263734,93031,NaN,EPAS1_Intron,1.0,NaN,NaN
182178,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,CLOCK,4,56315636.0,56315636.0,Missense_Mutation,SNP,G,G,A,ENST00000309964.4:c.1376C>T,p.T459M,ENST00000309964,119236,NaN,CLOCK_Missense_Mutation,1.0,459.0,459.0
182198,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,HCFC2,12,104492158.0,104492158.0,Missense_Mutation,SNP,C,C,T,ENST00000229330.4:c.1778C>T,p.A593V,ENST00000229330,40405,NaN,HCFC2_Missense_Mutation,1.0,593.0,593.0

In [20]:
data_mutation_SINIFICANTgenes_bothTNandNONTN_p_005.PATIENT_ID.nunique()

1508

19 (1527-1508) ductal patients do not carry mutations on the significant genes with p-value < 0.05 selected by MutSig2CV

In [21]:
data_mutation_SINIFICANTgenes_bothTNandNONTN_p_005.Hugo_Symbol.nunique()

1017

In [22]:
# look at the number of missing values in the dataframe 
data_mutation_SINIFICANTgenes_bothTNandNONTN_p_005.isna().sum()

PATIENT_ID                   0
Tumor_Sample_Barcode         0
Hugo_Symbol                  0
Chromosome                   0
Start_Position               0
End_Position                 0
Variant_Classification       0
Variant_Type                 0
Reference_Allele             0
Tumor_Seq_Allele1            0
Tumor_Seq_Allele2            0
HGVSc                      255
HGVSp_Short                298
Transcript_ID             7444
Gene_length                  0
ENSP                      8239
Hugo_variant                 0
Mutation_length              0
Protein_position_start     960
Protein_position_end       960
dtype: int64

8239 ENSP values are missing.

In [23]:
data_mutation_SINIFICANTgenes_bothTNandNONTN_P005_protein_pos = data_mutation_SINIFICANTgenes_bothTNandNONTN_p_005[['Protein_position_start']].copy()
data_mutation_SINIFICANTgenes_bothTNandNONTN_P005_protein_pos

        Protein_position_start
15                       342.0
18                      1069.0
22                       274.0
25                       503.0
26                       397.0
...                        ...
182145                  1470.0
182163                   333.0
182168                     NaN
182178                   459.0
182198                   593.0

[15134 rows x 1 columns]

In [24]:
data_mutation_SINIFICANTgenes_bothTNandNONTN_P005_protein_pos['Protein_position_start'] = pd.to_numeric(data_mutation_SINIFICANTgenes_bothTNandNONTN_P005_protein_pos['Protein_position_start'])

In [25]:
# let's focus on the two columns Hugo Symbol and ENSP
data_mutation_SINIFICANTgenes_bothTNandNONTN_P005_gene_ENSP = data_mutation_SINIFICANTgenes_bothTNandNONTN_p_005[['Hugo_Symbol', 'ENSP']].copy()
data_mutation_SINIFICANTgenes_bothTNandNONTN_P005_gene_ENSP

       Hugo_Symbol ENSP
15            TP53  NaN
18          PIK3CA  NaN
22            TP53  NaN
25           MAML3  NaN
26           SF3B4  NaN
...            ...  ...
182145       SOGA2  NaN
182163       GATA3  NaN
182168       EPAS1  NaN
182178       CLOCK  NaN
182198       HCFC2  NaN

[15134 rows x 2 columns]

In [26]:
# sostituisci i missing values nella colonna ENSP con la parola 'VUOTO'
def sostituzione_nan (df_relevant_genes_HS_ENSP):

    for index, row in df_relevant_genes_HS_ENSP.iterrows():
        gene = row.Hugo_Symbol
        ENSP =  str(row.ENSP)
    #print(type(ENSP))
        if ENSP.startswith('ENSP') is False:
            df_relevant_genes_HS_ENSP.loc[index, 'ENSP'] = 'VUOTO' # se non c'è l'ENSP della proteina metti 'VUOTO'
            #count_nan = count_nan+1
    return (df_relevant_genes_HS_ENSP)

In [27]:
# substitute the ENSP NaN with 'VUOTO'
data_mutation_SINIFICANTgenes_bothTNandNONTN_P005_gene_ENSP_nonan = sostituzione_nan(data_mutation_SINIFICANTgenes_bothTNandNONTN_P005_gene_ENSP)
data_mutation_SINIFICANTgenes_bothTNandNONTN_P005_gene_ENSP_nonan

       Hugo_Symbol   ENSP
15            TP53  VUOTO
18          PIK3CA  VUOTO
22            TP53  VUOTO
25           MAML3  VUOTO
26           SF3B4  VUOTO
...            ...    ...
182145       SOGA2  VUOTO
182163       GATA3  VUOTO
182168       EPAS1  VUOTO
182178       CLOCK  VUOTO
182198       HCFC2  VUOTO

[15134 rows x 2 columns]

In [28]:
(data_mutation_SINIFICANTgenes_bothTNandNONTN_P005_gene_ENSP_nonan['ENSP']=='VUOTO').sum()

8239

In [29]:
## The function Vett_transcript takes all the unique Hugo Symbols as indexes and create the column 'Protein length' filled with zeros 
def Index_relevant_genes (df_mut):
    vett_Hugo_symbols_relevant = df_mut.Hugo_Symbol.unique()
    df_vett_Hugo_symbols_relevant = pd.DataFrame(index = vett_Hugo_symbols_relevant, columns = ['Protein_length'])
    df_vett_Hugo_symbols_relevant = df_vett_Hugo_symbols_relevant.fillna(0)
    return (df_vett_Hugo_symbols_relevant)

In [30]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005 = Index_relevant_genes(data_mutation_SINIFICANTgenes_bothTNandNONTN_P005_gene_ENSP_nonan)
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005

          Protein_length
TP53                   0
PIK3CA                 0
MAML3                  0
SF3B4                  0
TTN                    0
...                  ...
SPG21                  0
PFDN5                  0
CCNT2                  0
CSN2                   0
KRTAP5-1               0

[1017 rows x 1 columns]

### Retrieve the protein length using pyensembl

In [31]:
from pyensembl import EnsemblRelease

data = EnsemblRelease(75)

def protein_length_computation(vett_relevant_genes, df_relevant_genes_HS_ENSP_nonan):
    
    for index, row in vett_relevant_genes.iterrows():
        gene = index
        length = row.Protein_length
        if length == 0:
            df = df_relevant_genes_HS_ENSP_nonan[df_relevant_genes_HS_ENSP_nonan['Hugo_Symbol'] == gene]
            for index, row in df.iterrows():
                ENSP_singolo = row.ENSP
                if ENSP_singolo != 'VUOTO':
                #print(ENSP_singolo)
                    protein = data.protein_sequence(ENSP_singolo)
                    protein_length = len(protein)
                    vett_relevant_genes.loc[gene, 'Protein_length'] = protein_length

In [32]:
protein_length_computation(Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005, data_mutation_SINIFICANTgenes_bothTNandNONTN_P005_gene_ENSP_nonan)

INFO:pyensembl.sequence_data:Loaded sequence dictionary from C:\Users\Cristina\AppData\Local\pyensembl\GRCh37\ensembl75\pyensembl\GRCh37\ensembl75\Cache\Homo_sapiens.GRCh37.75.pep.all.fa.gz.pickle

In [33]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005

          Protein_length
TP53                 393
PIK3CA              1068
MAML3               1138
SF3B4                424
TTN                35991
...                  ...
SPG21                  0
PFDN5                  0
CCNT2                  0
CSN2                   0
KRTAP5-1               0

[1017 rows x 1 columns]

In [34]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005.loc[Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005['Protein_length']== 0]

          Protein_length
ZNF19                  0
C5orf48                0
CDKN2A                 0
SAMD11                 0
KRTAP9-8               0
LOR                    0
RPS3A                  0
NBL1                   0
OR9K2                  0
S100A7                 0
PTRH1                  0
TYROBP                 0
SMTNL2                 0
LUC7L2                 0
LINGO3                 0
HCRT                   0
FUT1                   0
WDR38                  0
SPG21                  0
PFDN5                  0
CCNT2                  0
CSN2                   0
KRTAP5-1               0

In [35]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005.loc['CDKN2A','Protein_length'] = 156

In [36]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005.loc['KRTAP5-1','Protein_length'] = 278

In [37]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005.loc['ZNF19','Protein_length'] = 458

In [38]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005.loc['LINGO3','Protein_length'] = 592

In [39]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005.loc['C5orf48','Protein_length'] = 134

In [40]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005.loc['SAMD11','Protein_length'] = 681

In [41]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005.loc['KRTAP9-8','Protein_length'] = 159

In [42]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005.loc['LOR','Protein_length'] = 312

In [43]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005.loc['RPS3A','Protein_length'] = 264

In [44]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005.loc['NBL1','Protein_length'] = 181

In [45]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005.loc['S100A7','Protein_length'] = 101

In [46]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005.loc['OR9K2','Protein_length'] = 335

In [47]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005.loc['PTRH1','Protein_length'] = 214

In [48]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005.loc['TYROBP','Protein_length'] = 113

In [49]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005.loc['SMTNL2','Protein_length'] = 461

In [50]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005.loc['LUC7L2','Protein_length'] = 392

In [51]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005.loc['HCRT','Protein_length'] = 131

In [52]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005.loc['WDR38','Protein_length'] = 314

In [53]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005.loc['FUT1','Protein_length'] = 365

In [54]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005.loc['SPG21','Protein_length'] = 308

In [55]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005.loc['PFDN5','Protein_length'] = 154

In [56]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005.loc['CCNT2','Protein_length'] = 730

In [57]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005.loc['CSN2','Protein_length'] = 226

In [58]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005.loc[Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005['Protein_length']== 0]

Empty DataFrame
Columns: [Protein_length]
Index: []

In [59]:
data_mutation_SINIFICANTgenes_bothTNandNONTN_p_005['Protein_position_start'].isna().sum()

960

In [60]:
# Define a function that takes in input the mutation dataset containing only the relevant genes and gives in output a new df containing HugoSymbol e Protein Position
def protein_position_Hugo_Symbol_only(relevant_mutations):
    df_positions = []

    for index, row in relevant_mutations.iterrows():
        df_positions.append([row.Hugo_Symbol, row.Protein_position_start])
    
    df_positions = pd.DataFrame(df_positions, columns = ['symbol', 'position'])
    df_positions = df_positions.dropna() # drop the protein position missing values 
    
    # Convert single column to int dtype
    df_positions['position'] = pd.to_numeric(df_positions['position'])
    df_positions = df_positions.astype({"position":"int"})
    
    return (df_positions)

In [61]:
protein_position_hugoSymbols_totalTNandNONTN_P005 = protein_position_Hugo_Symbol_only(data_mutation_SINIFICANTgenes_bothTNandNONTN_p_005)
protein_position_hugoSymbols_totalTNandNONTN_P005

       symbol  position
0        TP53       342
1      PIK3CA      1069
2        TP53       274
3       MAML3       503
4       SF3B4       397
...       ...       ...
15128   TEX14      1174
15129   SOGA2      1470
15130   GATA3       333
15132   CLOCK       459
15133   HCFC2       593

[14174 rows x 2 columns]

In [62]:
# save the dataset 
os.chdir("C:/Users/Cristina/OneDrive/Documenti/BCG/Tesi/MutClust_input_definitivo")
protein_position_hugoSymbols_totalTNandNONTN_P005.to_csv("Symbol_ProteinPosition_onlyHugoSymbol_totalTNandnonTN_pval005_definitivo.txt", index=False, sep='\t')

In [63]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005

          Protein_length
TP53                 393
PIK3CA              1068
MAML3               1138
SF3B4                424
TTN                35991
...                  ...
SPG21                308
PFDN5                154
CCNT2                730
CSN2                 226
KRTAP5-1             278

[1017 rows x 1 columns]

In [64]:
# add the Protein_length column to the relevant mutation dataset 
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005.reset_index(level=0, inplace=True)
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005.rename(columns={"index": "Hugo_Symbol"}, inplace=True)
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005

     Hugo_Symbol  Protein_length
0           TP53             393
1         PIK3CA            1068
2          MAML3            1138
3          SF3B4             424
4            TTN           35991
...          ...             ...
1012       SPG21             308
1013       PFDN5             154
1014       CCNT2             730
1015        CSN2             226
1016    KRTAP5-1             278

[1017 rows x 2 columns]

In [65]:
# add the protein lengths to the mutation dataset 
data_mutation_SINIFICANTgenes_bothTNandNONTN_p_005 = data_mutation_SINIFICANTgenes_bothTNandNONTN_p_005.join(Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_P005.set_index('Hugo_Symbol'), on='Hugo_Symbol')
data_mutation_SINIFICANTgenes_bothTNandNONTN_p_005

,PATIENT_ID,Tumor_Sample_Barcode,Hugo_Symbol,Chromosome,Start_Position,End_Position,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,...,HGVSc,HGVSp_Short,Transcript_ID,Gene_length,ENSP,Hugo_variant,Mutation_length,Protein_position_start,Protein_position_end,Protein_length
15,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,TP53,17,7574003.0,7574003.0,Nonsense_Mutation,SNP,G,G,...,ENST00000269305.4:c.1024C>T,p.R342*,ENST00000269305,25760,NaN,TP53_Nonsense_Mutation,1.0,342.0,342.0,393
18,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,PIK3CA,3,178952150.0,178952151.0,Frame_Shift_Ins,INS,-,-,...,ENST00000263967.3:c.3205_3206insTTTT,p.*1069Ffs*5,ENST00000263967,91980,NaN,PIK3CA_Frame_Shift_Ins,2.0,1069.0,1069.0,1068
22,brca_smc_2018_BB01_004,brca_smc_2018_BB01_004,TP53,17,7577117.0,7577117.0,Missense_Mutation,SNP,A,A,...,ENST00000269305.4:c.821T>G,p.V274G,ENST00000269305,25760,NaN,TP53_Missense_Mutation,1.0,274.0,274.0,393
25,brca_smc_2018_BB01_004,brca_smc_2018_BB01_004,MAML3,4,140811082.0,140811083.0,In_Frame_Ins,INS,-,-,...,ENST00000509479.2:c.1508_1509insCAA,p.Q503delinsHK,ENST00000509479,437432,NaN,MAML3_In_Frame_Ins,2.0,503.0,503.0,1138
26,brca_smc_2018_BB01_005,brca_smc_2018_BB01_005,SF3B4,1,149895518.0,149895518.0,Missense_Mutation,SNP,C,C,...,ENST00000271628.8:c.1191G>T,p.Q397H,ENST00000271628,5028,NaN,SF3B4_Missense_Mutation,1.0,397.0,397.0,424
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182145,MBCProject_ygcMFgCR,RP-1156_MBCProject_ygcMFgCR_T1A_v1_Exome,SOGA2,18,8824961.0,8824961.0,Silent,SNP,C,C,...,ENST00000306329.11:c.4410C>G,p.P1470=,ENST00000306329,127118,NaN,SOGA2_Silent,1.0,1470.0,1470.0,1586
182163,MBCProject_ygcMFgCR,RP-1156_MBCProject_ygcMFgCR_T1A_v1_Exome,GATA3,10,8111513.0,8111514.0,Frame_Shift_Ins,INS,-,-,...,ENST00000346208.3:c.1003dup,p.D335Gfs*17,ENST00000346208,21595,NaN,GATA3_Frame_Shift_Ins,2.0,333.0,333.0,444
182168,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,EPAS1,2,46525087.0,46525087.0,Intron,SNP,G,G,...,ENST00000263734.3:c.26+11G>A,p.*9*,ENST00000263734,93031,NaN,EPAS1_Intron,1.0,NaN,NaN,870
182178,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,CLOCK,4,56315636.0,56315636.0,Missense_Mutation,SNP,G,G,...,ENST00000309964.4:c.1376C>T,p.T459M,ENST00000309964,119236,NaN,CLOCK_Missense_Mutation,1.0,459.0,459.0,846
182198,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,HCFC2,12,104492158.0,104492158.0,Missense_Mutation,SNP,C,C,...,ENST00000229330.4:c.1778C>T,p.A593V,ENST00000229330,40405,NaN,HCFC2_Missense_Mutation,1.0,593.0,593.0,792

In [66]:
# save the dataset 
os.chdir("C:/Users/Cristina/OneDrive/Documenti/BCG/Tesi/MutClust_input_definitivo")
data_mutation_SINIFICANTgenes_bothTNandNONTN_p_005.to_csv("data_mutation_SINIFICANTgenes_ONLYhugo_bothTNandNONTN_P005_definitivo.txt", index=False, sep='\t')

In [67]:
data_mutation_SINIFICANTgenes_bothTNandNONTN_p_005.Variant_Classification.nunique()

16

In [68]:
data_mutation_SINIFICANTgenes_bothTNandNONTN_p_005.Variant_Classification.unique()

array(['Nonsense_Mutation', 'Frame_Shift_Ins', 'Missense_Mutation',
       'In_Frame_Ins', 'Frame_Shift_Del', 'Splice_Site', 'In_Frame_Del',
       'Nonstop_Mutation', "5'UTR", 'Translation_Start_Site', 'Silent',
       'Intron', 'Splice_Region', "3'UTR", "5'Flank", "3'Flank"],
      dtype=object)

In [69]:
# Define a function that gives in output a new df containing HugoSymbol e Protein Length
def protein_length_only_Hugo_Symbol(relevant_mutations):  
    df_protein_lengths = []
    

    for index, row in relevant_mutations.iterrows():
        df_protein_lengths.append([row.Hugo_Symbol, row.Protein_length])
    
    df_protein_lengths = pd.DataFrame(df_protein_lengths, columns = ['symbol', 'length'])
    df_protein_lengths = df_protein_lengths.dropna()
    df_protein_lengths =  df_protein_lengths.drop_duplicates()
    
    return (df_protein_lengths)

In [70]:
relevant_ONLYHugoSymbols_ProteinLength_allTNandNONTN_P005 = protein_length_only_Hugo_Symbol(data_mutation_SINIFICANTgenes_bothTNandNONTN_p_005)
relevant_ONLYHugoSymbols_ProteinLength_allTNandNONTN_P005

         symbol  length
0          TP53     393
1        PIK3CA    1068
3         MAML3    1138
4         SF3B4     424
5           TTN   35991
...         ...     ...
12230     SPG21     308
12323     PFDN5     154
12471     CCNT2     730
13076      CSN2     226
13407  KRTAP5-1     278

[1017 rows x 2 columns]

In [71]:
relevant_ONLYHugoSymbols_ProteinLength_allTNandNONTN_P005.isna().sum()

symbol    0
length    0
dtype: int64

In [72]:
# save the dataset 
os.chdir("C:/Users/Cristina/OneDrive/Documenti/BCG/Tesi/MutClust_input_definitivo")
relevant_ONLYHugoSymbols_ProteinLength_allTNandNONTN_P005.to_csv("Symbol_ProteinLength_relevantONLYhugosymbols_TNandNONTN_p005_definitivo.txt", index=False, sep='\t')

### 2. q-value < 1

In [73]:
data_mutation_total_ductal_nohypo_nohyper

,PATIENT_ID,Tumor_Sample_Barcode,Hugo_Symbol,Chromosome,Start_Position,End_Position,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Transcript_ID,Gene_length,ENSP,Hugo_variant,Mutation_length,Protein_position_start,Protein_position_end
0,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,KALRN,3,123988087.0,123988087.0,Missense_Mutation,SNP,G,G,C,ENST00000240874.3:c.948G>C,p.E316D,ENST00000240874,646303,NaN,KALRN_Missense_Mutation,1.0,316.0,316.0
1,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,ANK2,4,114195720.0,114195720.0,Missense_Mutation,SNP,C,C,T,ENST00000357077.4:c.1598C>T,p.P533L,ENST00000357077,565632,NaN,ANK2_Missense_Mutation,1.0,533.0,533.0
2,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,SORBS2,4,186539742.0,186539742.0,Missense_Mutation,SNP,G,G,C,ENST00000355634.5:c.2936C>G,p.S979C,ENST00000355634,371209,NaN,SORBS2_Missense_Mutation,1.0,979.0,979.0
3,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,PCDHA11,5,140250828.0,140250828.0,Missense_Mutation,SNP,C,C,G,ENST00000398640.2:c.2140C>G,p.L714V,ENST00000398640,143241,NaN,PCDHA11_Missense_Mutation,1.0,714.0,714.0
4,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,WRNIP1,6,2766210.0,2766210.0,Missense_Mutation,SNP,C,C,A,ENST00000380773.4:c.354C>A,p.S118R,ENST00000380773,21539,NaN,WRNIP1_Missense_Mutation,1.0,118.0,118.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182216,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,NRSN2,20,333991.0,333991.0,Silent,SNP,C,C,T,ENST00000382285.2:c.327C>T,p.N109=,ENST00000382285,12879,NaN,NRSN2_Silent,1.0,109.0,109.0
182217,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,CHRNA4,20,61986887.0,61986887.0,Intron,SNP,G,G,C,ENST00000370263.4:c.383+440C>G,p.*128*,ENST00000370263,34334,NaN,CHRNA4_Intron,1.0,NaN,NaN
182218,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,CHRNA4,20,61987386.0,61987386.0,Silent,SNP,G,G,A,ENST00000370263.4:c.324C>T,p.V108=,ENST00000370263,34334,NaN,CHRNA4_Silent,1.0,108.0,108.0
182219,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,KCNQ2,20,62078103.0,62078103.0,Silent,SNP,G,G,A,ENST00000359125.2:c.384C>T,p.I128=,ENST00000359125,66452,NaN,KCNQ2_Silent,1.0,128.0,128.0
182220,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,XBP1,22,29191563.0,29191563.0,Nonsense_Mutation,SNP,G,G,A,ENST00000216037.6:c.757C>T,p.Q253*,ENST00000216037,6043,NaN,XBP1_Nonsense_Mutation,1.0,253.0,253.0

In [74]:
# load the significant genes (TN + non TN) with q-val < 1
os.chdir("C:/Users/Cristina/OneDrive/Documenti/BCG/Tesi/Significant genes_definitivo")
significant_genes_TNandNONTN_qval_1 = pd.read_csv('significant_genes_totalTNandNONTN_qval_1_definitivo.csv', sep=',', engine='python')
significant_genes_TNandNONTN_qval_1

    Hugo_Symbol
0          TP53
1           RB1
2        PIK3CA
3         FBXW7
4          PTEN
..          ...
304       SF3B3
305        GRM2
306     FAM193A
307      TFAP2A
308        SGK2

[309 rows x 1 columns]

In [75]:
significant_genes_TNandNONTN_qval_1['Hugo_Symbol'] = significant_genes_TNandNONTN_qval_1['Hugo_Symbol'].replace('EPPIN-WFDC6', 'EPPIN')

In [76]:
significant_genes_TNandNONTN_qval_1['Hugo_Symbol']  = significant_genes_TNandNONTN_qval_1['Hugo_Symbol'].replace(['EIF3CL'], ['EIF3C'])

In [77]:
# study if there are gene names inconsistencies between relevant genes with q-val < 1 and total ductal genes 
pd.merge(significant_genes_TNandNONTN_qval_1, unique_genes_total_ductal, how='inner', on=['Hugo_Symbol'])

    Hugo_Symbol
0          TP53
1           RB1
2        PIK3CA
3         FBXW7
4          PTEN
..          ...
304       SF3B3
305        GRM2
306     FAM193A
307      TFAP2A
308        SGK2

[309 rows x 1 columns]

There are not gene names' inconsistencies

In [78]:
significant_genes_TNandNONTN_qval_1_array = significant_genes_TNandNONTN_qval_1['Hugo_Symbol'].values
significant_genes_TNandNONTN_qval_1_array

array(['TP53', 'RB1', 'PIK3CA', 'FBXW7', 'PTEN', 'BRCA1', 'CDKN2A',
       'MYL10', 'ZKSCAN1', 'MGAT5B', 'MAML3', 'NOTCH2', 'NBN', 'STAB2',
       'RAB42', 'ATG4C', 'PIK3R1', 'C6orf118', 'LZTR1', 'MTMR12',
       'NUP153', 'COIL', 'ZNF195', 'GATA3', 'MAP2K4', 'MAP3K1', 'CDH1',
       'KMT2C', 'CBFB', 'AKT1', 'NCOR1', 'ARID1A', 'ESR1', 'ZNF19',
       'SPEN', 'MYH9', 'TBX3', 'CTCF', 'KRAS', 'NF1', 'FAM208B', 'GPS2',
       'SF3B1', 'ATM', 'CDKN1B', 'ERBB2', 'RBM27', 'BRCA2', 'OR5K4',
       'SPRED2', 'RUNX1', 'MEN1', 'ERBB3', 'HIST1H3B', 'CHD9', 'KIAA0195',
       'ASXL2', 'KMT2E', 'RAD54B', 'BPIFB2', 'ZNF208', 'E2F4', 'TARBP2',
       'PRB2', 'LIPH', 'FANCD2', 'PLK2', 'USP8', 'SP3', 'HCFC2', 'PLTP',
       'FAM49B', 'NUP93', 'TFDP1', 'PTPN22', 'SYBU', 'DIAPH1', 'PODXL',
       'FIGNL1', 'CXorf38', 'ORC2', 'RIC8A', 'PNN', 'TSC1', 'PRKCZ',
       'MYB', 'ACLY', 'FHDC1', 'SLFN13', 'RABEP1', 'MBD6', 'MAP4K1',
       'ACACB', 'SNX16', 'MCRS1', 'RSBN1L', 'MTHFD1L', 'TAF7L', 'XPO4',
       'NIPBL', 'METTL7B', 'SEC63', 'FOXP1', 'SLC45A1', 'SUPT16H',
       'LPCAT4', 'ANKHD1', 'COL17A1', 'DAP3', 'DOCK11', 'ZNF814', 'CUL7',
       'SMG1', 'FASTKD2', 'TBC1D8', 'IL24', 'AP4M1', 'RGS11', 'RPL5',
       'DNAH12', 'MTA2', 'FOXA1', 'GLDC', 'DCST1', 'NDUFB6', 'NME5',
       'FABP1', 'CCDC135', 'BYSL', 'OR4D10', 'ZFHX3', 'TBL1XR1', 'AKR1C3',
       'TH', 'ZC3H4', 'GRB10', 'KRTAP5-1', 'PKN2', 'JMJD6', 'LRCH3',
       'APLF', 'MED23', 'TMEM120B', 'NKX3-2', 'OSBPL8', 'TRIP11', 'UBAP2',
       'FAM166B', 'SZT2', 'PODXL2', 'KIAA0355', 'TSSK3', 'CYP3A4',
       'FKBP4', 'FGFR2', 'GPRIN1', 'IBSP', 'MAP4K3', 'STAG2', 'GBGT1',
       'COL2A1', 'SMAD4', 'ATAD2B', 'SF3B4', 'FMO5', 'AGO1', 'SNAPC1',
       'PALB2', 'COL4A2', 'ICOSLG', 'PIK3C2A', 'SEC13', 'HSD17B11',
       'RPGRIP1', 'GAS8', 'GARNL3', 'SMTNL2', 'TET3', 'HIST1H3D', 'INADL',
       'NAA15', 'LINGO3', 'ZMYND8', 'PTGS2', 'ITPR3', 'ARRDC1', 'PTCD3',
       'STAT2', 'OR6B1', 'EPG5', 'CEP152', 'ATF6', 'RAPGEF4', 'CARD6',
       'SLC4A2', 'ZW10', 'SPOPL', 'EFS', 'ACVR2A', 'TRA2B', 'ITPKB',
       'SIRT7', 'ZNF546', 'CHRM1', 'AP1S3', 'CDC73', 'USP42', 'UQCR10',
       'S100A7', 'MATN4', 'EML2', 'PSIP1', 'MSH5', 'FCHO1', 'PEX11G',
       'WDR44', 'JAK1', 'SLC25A19', 'DDX11', 'TYRP1', 'TRAPPC10', 'EPHX3',
       'ZNF716', 'SAMD14', 'CDK19', 'IL25', 'IL31RA', 'SMARCA1', 'BLK',
       'TUBD1', 'KLF4', 'ADORA3', 'LRRC43', 'GLT6D1', 'ESF1', 'SLC28A2',
       'PLS3', 'FBRSL1', 'BRD7', 'KRT79', 'KRT6B', 'DNASE1L3', 'ATP8B1',
       'KLHDC2', 'TRPM8', 'WDR47', 'MRGPRX4', 'CAPN2', 'TRAPPC12', 'EML5',
       'CCT6B', 'ASH1L', 'FSHR', 'LRRC16B', 'NCOA6', 'COL5A3', 'C3orf70',
       'HSP90B1', 'SELP', 'PLIN2', 'ANKRD37', 'SLC6A11', 'OR52N2', 'CA14',
       'HPD', 'MTHFD1', 'ZBTB48', 'EIF3C', 'SUCO', 'ABCG2', 'CCNT1',
       'FGF18', 'HSPA5', 'CFTR', 'TRAF3', 'B2M', 'USP15', 'TSC22D1',
       'PLA2G4D', 'RCC2', 'ZNF230', 'KDELC2', 'TMEM132C', 'SLC26A9',
       'FBXO18', 'KIAA1109', 'HMBS', 'CCDC82', 'OR2B6', 'TMEM87B',
       'PBRM1', 'OSBPL1A', 'WBP11', 'FAM107B', 'CTTN', 'EWSR1', 'TNC',
       'EP300', 'ATL3', 'ILF2', 'LAMB3', 'GNL3L', 'VWF', 'KIF1B', 'SF3B3',
       'GRM2', 'FAM193A', 'TFAP2A', 'SGK2'], dtype=object)

In [79]:
len(significant_genes_TNandNONTN_qval_1_array)

309

### Preparation of the dataset for MutClust

In [80]:
# select the total ductal mutations belonging to the relevant genes found by MutSig (p-value < 0.05)
data_mutation_SINIFICANTgenes_bothTNandNONTN_q_1= data_mutation_total_ductal_nohypo_nohyper[data_mutation_total_ductal_nohypo_nohyper['Hugo_Symbol'].isin(significant_genes_TNandNONTN_qval_1_array)]
data_mutation_SINIFICANTgenes_bothTNandNONTN_q_1

,PATIENT_ID,Tumor_Sample_Barcode,Hugo_Symbol,Chromosome,Start_Position,End_Position,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Transcript_ID,Gene_length,ENSP,Hugo_variant,Mutation_length,Protein_position_start,Protein_position_end
15,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,TP53,17,7574003.0,7574003.0,Nonsense_Mutation,SNP,G,G,A,ENST00000269305.4:c.1024C>T,p.R342*,ENST00000269305,25760,NaN,TP53_Nonsense_Mutation,1.0,342.0,342.0
18,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,PIK3CA,3,178952150.0,178952151.0,Frame_Shift_Ins,INS,-,-,TTTT,ENST00000263967.3:c.3205_3206insTTTT,p.*1069Ffs*5,ENST00000263967,91980,NaN,PIK3CA_Frame_Shift_Ins,2.0,1069.0,1069.0
22,brca_smc_2018_BB01_004,brca_smc_2018_BB01_004,TP53,17,7577117.0,7577117.0,Missense_Mutation,SNP,A,A,C,ENST00000269305.4:c.821T>G,p.V274G,ENST00000269305,25760,NaN,TP53_Missense_Mutation,1.0,274.0,274.0
25,brca_smc_2018_BB01_004,brca_smc_2018_BB01_004,MAML3,4,140811082.0,140811083.0,In_Frame_Ins,INS,-,-,TGT,ENST00000509479.2:c.1508_1509insCAA,p.Q503delinsHK,ENST00000509479,437432,NaN,MAML3_In_Frame_Ins,2.0,503.0,503.0
26,brca_smc_2018_BB01_005,brca_smc_2018_BB01_005,SF3B4,1,149895518.0,149895518.0,Missense_Mutation,SNP,C,C,A,ENST00000271628.8:c.1191G>T,p.Q397H,ENST00000271628,5028,NaN,SF3B4_Missense_Mutation,1.0,397.0,397.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182026,MBCProject_ygcMFgCR,RP-1156_MBCProject_ygcMFgCR_T1A_v1_Exome,LAMB3,1,209801520.0,209801520.0,Missense_Mutation,SNP,G,G,A,ENST00000356082.4:c.1148C>T,p.P383L,ENST00000356082,37597,NaN,LAMB3_Missense_Mutation,1.0,383.0,383.0
182066,MBCProject_ygcMFgCR,RP-1156_MBCProject_ygcMFgCR_T1A_v1_Exome,BYSL,6,41900245.0,41900245.0,Missense_Mutation,SNP,G,G,A,ENST00000230340.4:c.1115G>A,p.R372H,ENST00000230340,11859,NaN,BYSL_Missense_Mutation,1.0,372.0,372.0
182113,MBCProject_ygcMFgCR,RP-1156_MBCProject_ygcMFgCR_T1A_v1_Exome,FBRSL1,12,133151136.0,133151136.0,Nonsense_Mutation,SNP,C,C,T,ENST00000434748.2:c.1816C>T,p.Q606*,ENST00000434748,95638,NaN,FBRSL1_Nonsense_Mutation,1.0,606.0,606.0
182163,MBCProject_ygcMFgCR,RP-1156_MBCProject_ygcMFgCR_T1A_v1_Exome,GATA3,10,8111513.0,8111514.0,Frame_Shift_Ins,INS,-,-,G,ENST00000346208.3:c.1003dup,p.D335Gfs*17,ENST00000346208,21595,NaN,GATA3_Frame_Shift_Ins,2.0,333.0,333.0
182198,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,HCFC2,12,104492158.0,104492158.0,Missense_Mutation,SNP,C,C,T,ENST00000229330.4:c.1778C>T,p.A593V,ENST00000229330,40405,NaN,HCFC2_Missense_Mutation,1.0,593.0,593.0

In [81]:
data_mutation_SINIFICANTgenes_bothTNandNONTN_q_1.PATIENT_ID.nunique()

1457

70 (1527-1457) ductal patients do not carry mutations on the significant genes with q-value < 1 selected by MutSig2CV

In [82]:
data_mutation_SINIFICANTgenes_bothTNandNONTN_q_1.Hugo_Symbol.nunique()

309

In [83]:
# look at the number of missing values in the dataframe 
data_mutation_SINIFICANTgenes_bothTNandNONTN_q_1.isna().sum()

PATIENT_ID                   0
Tumor_Sample_Barcode         0
Hugo_Symbol                  0
Chromosome                   0
Start_Position               0
End_Position                 0
Variant_Classification       0
Variant_Type                 0
Reference_Allele             0
Tumor_Seq_Allele1            0
Tumor_Seq_Allele2            0
HGVSc                       67
HGVSp_Short                 82
Transcript_ID             3208
Gene_length                  0
ENSP                      4029
Hugo_variant                 0
Mutation_length              0
Protein_position_start     306
Protein_position_end       306
dtype: int64

4029 ENSP values are missing.

In [84]:
data_mutation_SINIFICANTgenes_bothTNandNONTN_Q1_protein_pos = data_mutation_SINIFICANTgenes_bothTNandNONTN_q_1[['Protein_position_start']].copy()
data_mutation_SINIFICANTgenes_bothTNandNONTN_Q1_protein_pos

        Protein_position_start
15                       342.0
18                      1069.0
22                       274.0
25                       503.0
26                       397.0
...                        ...
182026                   383.0
182066                   372.0
182113                   606.0
182163                   333.0
182198                   593.0

[6607 rows x 1 columns]

In [85]:
data_mutation_SINIFICANTgenes_bothTNandNONTN_Q1_protein_pos['Protein_position_start'] = pd.to_numeric(data_mutation_SINIFICANTgenes_bothTNandNONTN_Q1_protein_pos['Protein_position_start'])

In [86]:
# let's focus on the two columns Hugo Symbol and ENSP
data_mutation_SINIFICANTgenes_bothTNandNONTN_Q1_gene_ENSP = data_mutation_SINIFICANTgenes_bothTNandNONTN_q_1[['Hugo_Symbol', 'ENSP']].copy()
data_mutation_SINIFICANTgenes_bothTNandNONTN_Q1_gene_ENSP

       Hugo_Symbol ENSP
15            TP53  NaN
18          PIK3CA  NaN
22            TP53  NaN
25           MAML3  NaN
26           SF3B4  NaN
...            ...  ...
182026       LAMB3  NaN
182066        BYSL  NaN
182113      FBRSL1  NaN
182163       GATA3  NaN
182198       HCFC2  NaN

[6607 rows x 2 columns]

In [87]:
# substitute the ENSP NaN with 'VUOTO'
data_mutation_SINIFICANTgenes_bothTNandNONTN_Q1_gene_ENSP_nonan = sostituzione_nan(data_mutation_SINIFICANTgenes_bothTNandNONTN_Q1_gene_ENSP)
data_mutation_SINIFICANTgenes_bothTNandNONTN_Q1_gene_ENSP_nonan

       Hugo_Symbol   ENSP
15            TP53  VUOTO
18          PIK3CA  VUOTO
22            TP53  VUOTO
25           MAML3  VUOTO
26           SF3B4  VUOTO
...            ...    ...
182026       LAMB3  VUOTO
182066        BYSL  VUOTO
182113      FBRSL1  VUOTO
182163       GATA3  VUOTO
182198       HCFC2  VUOTO

[6607 rows x 2 columns]

In [88]:
(data_mutation_SINIFICANTgenes_bothTNandNONTN_Q1_gene_ENSP_nonan['ENSP']=='VUOTO').sum()

4029

In [89]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_Q1 = Index_relevant_genes(data_mutation_SINIFICANTgenes_bothTNandNONTN_Q1_gene_ENSP_nonan)
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_Q1

          Protein_length
TP53                   0
PIK3CA                 0
MAML3                  0
SF3B4                  0
NF1                    0
...                  ...
PLTP                   0
PODXL                  0
HMBS                   0
EIF3C                  0
KRTAP5-1               0

[309 rows x 1 columns]

### Retrieve the protein length using pyensembl

In [90]:
protein_length_computation(Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_Q1, data_mutation_SINIFICANTgenes_bothTNandNONTN_Q1_gene_ENSP_nonan)

In [91]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_Q1

          Protein_length
TP53                 393
PIK3CA              1068
MAML3               1138
SF3B4                424
NF1                 2839
...                  ...
PLTP                 493
PODXL                558
HMBS                 361
EIF3C                914
KRTAP5-1               0

[309 rows x 1 columns]

In [92]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_Q1.loc[Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_Q1['Protein_length']== 0]

          Protein_length
ZNF19                  0
CDKN2A                 0
S100A7                 0
SMTNL2                 0
LINGO3                 0
KRTAP5-1               0

In [93]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_Q1.loc['CDKN2A','Protein_length'] = 156

In [94]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_Q1.loc['KRTAP5-1','Protein_length'] = 278

In [95]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_Q1.loc['SMTNL2','Protein_length'] = 461

In [96]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_Q1.loc['LINGO3','Protein_length'] = 592

In [97]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_Q1.loc['ZNF19','Protein_length'] = 458

In [98]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_Q1.loc['S100A7','Protein_length'] = 101

In [99]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_Q1

          Protein_length
TP53                 393
PIK3CA              1068
MAML3               1138
SF3B4                424
NF1                 2839
...                  ...
PLTP                 493
PODXL                558
HMBS                 361
EIF3C                914
KRTAP5-1             278

[309 rows x 1 columns]

In [100]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_Q1.loc[Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_Q1['Protein_length']== 0]

Empty DataFrame
Columns: [Protein_length]
Index: []

In [101]:
data_mutation_SINIFICANTgenes_bothTNandNONTN_q_1['Protein_position_start'].isna().sum()

306

In [102]:
protein_position_hugoSymbols_totalTNandNONTN_Q1 = protein_position_Hugo_Symbol_only(data_mutation_SINIFICANTgenes_bothTNandNONTN_q_1)
protein_position_hugoSymbols_totalTNandNONTN_Q1

      symbol  position
0       TP53       342
1     PIK3CA      1069
2       TP53       274
3      MAML3       503
4      SF3B4       397
...      ...       ...
6602   LAMB3       383
6603    BYSL       372
6604  FBRSL1       606
6605   GATA3       333
6606   HCFC2       593

[6301 rows x 2 columns]

In [103]:
# save the dataset 
os.chdir("C:/Users/Cristina/OneDrive/Documenti/BCG/Tesi/MutClust_input_definitivo")
protein_position_hugoSymbols_totalTNandNONTN_Q1.to_csv("Symbol_ProteinPosition_onlyHugoSymbol_totalTNandnonTN_qval1_definitivo.txt", index=False, sep='\t')

In [104]:
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_Q1

          Protein_length
TP53                 393
PIK3CA              1068
MAML3               1138
SF3B4                424
NF1                 2839
...                  ...
PLTP                 493
PODXL                558
HMBS                 361
EIF3C                914
KRTAP5-1             278

[309 rows x 1 columns]

In [105]:
# add the Protein_length column to the relevant mutation dataset 
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_Q1.reset_index(level=0, inplace=True)
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_Q1.rename(columns={"index": "Hugo_Symbol"}, inplace=True)
Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_Q1

    Hugo_Symbol  Protein_length
0          TP53             393
1        PIK3CA            1068
2         MAML3            1138
3         SF3B4             424
4           NF1            2839
..          ...             ...
304        PLTP             493
305       PODXL             558
306        HMBS             361
307       EIF3C             914
308    KRTAP5-1             278

[309 rows x 2 columns]

In [106]:
# add the protein lengths to the mutation dataset 
data_mutation_SINIFICANTgenes_bothTNandNONTN_q_1 = data_mutation_SINIFICANTgenes_bothTNandNONTN_q_1.join(Hugo_symbols_relevant_SIGNIFICANT_genes_bothTNandNONTN_Q1.set_index('Hugo_Symbol'), on='Hugo_Symbol')
data_mutation_SINIFICANTgenes_bothTNandNONTN_q_1

,PATIENT_ID,Tumor_Sample_Barcode,Hugo_Symbol,Chromosome,Start_Position,End_Position,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,...,HGVSc,HGVSp_Short,Transcript_ID,Gene_length,ENSP,Hugo_variant,Mutation_length,Protein_position_start,Protein_position_end,Protein_length
15,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,TP53,17,7574003.0,7574003.0,Nonsense_Mutation,SNP,G,G,...,ENST00000269305.4:c.1024C>T,p.R342*,ENST00000269305,25760,NaN,TP53_Nonsense_Mutation,1.0,342.0,342.0,393
18,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,PIK3CA,3,178952150.0,178952151.0,Frame_Shift_Ins,INS,-,-,...,ENST00000263967.3:c.3205_3206insTTTT,p.*1069Ffs*5,ENST00000263967,91980,NaN,PIK3CA_Frame_Shift_Ins,2.0,1069.0,1069.0,1068
22,brca_smc_2018_BB01_004,brca_smc_2018_BB01_004,TP53,17,7577117.0,7577117.0,Missense_Mutation,SNP,A,A,...,ENST00000269305.4:c.821T>G,p.V274G,ENST00000269305,25760,NaN,TP53_Missense_Mutation,1.0,274.0,274.0,393
25,brca_smc_2018_BB01_004,brca_smc_2018_BB01_004,MAML3,4,140811082.0,140811083.0,In_Frame_Ins,INS,-,-,...,ENST00000509479.2:c.1508_1509insCAA,p.Q503delinsHK,ENST00000509479,437432,NaN,MAML3_In_Frame_Ins,2.0,503.0,503.0,1138
26,brca_smc_2018_BB01_005,brca_smc_2018_BB01_005,SF3B4,1,149895518.0,149895518.0,Missense_Mutation,SNP,C,C,...,ENST00000271628.8:c.1191G>T,p.Q397H,ENST00000271628,5028,NaN,SF3B4_Missense_Mutation,1.0,397.0,397.0,424
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182026,MBCProject_ygcMFgCR,RP-1156_MBCProject_ygcMFgCR_T1A_v1_Exome,LAMB3,1,209801520.0,209801520.0,Missense_Mutation,SNP,G,G,...,ENST00000356082.4:c.1148C>T,p.P383L,ENST00000356082,37597,NaN,LAMB3_Missense_Mutation,1.0,383.0,383.0,1172
182066,MBCProject_ygcMFgCR,RP-1156_MBCProject_ygcMFgCR_T1A_v1_Exome,BYSL,6,41900245.0,41900245.0,Missense_Mutation,SNP,G,G,...,ENST00000230340.4:c.1115G>A,p.R372H,ENST00000230340,11859,NaN,BYSL_Missense_Mutation,1.0,372.0,372.0,437
182113,MBCProject_ygcMFgCR,RP-1156_MBCProject_ygcMFgCR_T1A_v1_Exome,FBRSL1,12,133151136.0,133151136.0,Nonsense_Mutation,SNP,C,C,...,ENST00000434748.2:c.1816C>T,p.Q606*,ENST00000434748,95638,NaN,FBRSL1_Nonsense_Mutation,1.0,606.0,606.0,1045
182163,MBCProject_ygcMFgCR,RP-1156_MBCProject_ygcMFgCR_T1A_v1_Exome,GATA3,10,8111513.0,8111514.0,Frame_Shift_Ins,INS,-,-,...,ENST00000346208.3:c.1003dup,p.D335Gfs*17,ENST00000346208,21595,NaN,GATA3_Frame_Shift_Ins,2.0,333.0,333.0,444
182198,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,HCFC2,12,104492158.0,104492158.0,Missense_Mutation,SNP,C,C,...,ENST00000229330.4:c.1778C>T,p.A593V,ENST00000229330,40405,NaN,HCFC2_Missense_Mutation,1.0,593.0,593.0,792

In [107]:
# save the dataset 
os.chdir("C:/Users/Cristina/OneDrive/Documenti/BCG/Tesi/MutClust_input_definitivo")
data_mutation_SINIFICANTgenes_bothTNandNONTN_q_1.to_csv("data_mutation_SINIFICANTgenes_ONLYhugo_bothTNandNONTN_Q1_definitivo.txt", index=False, sep='\t')

In [108]:
data_mutation_SINIFICANTgenes_bothTNandNONTN_q_1.Variant_Classification.nunique()

16

In [109]:
relevant_ONLYHugoSymbols_ProteinLength_allTNandNONTN_Q1 = protein_length_only_Hugo_Symbol(data_mutation_SINIFICANTgenes_bothTNandNONTN_q_1)
relevant_ONLYHugoSymbols_ProteinLength_allTNandNONTN_Q1

        symbol  length
0         TP53     393
1       PIK3CA    1068
3        MAML3    1138
4        SF3B4     424
7          NF1    2839
...        ...     ...
3096      PLTP     493
3505     PODXL     558
3748      HMBS     361
4585     EIF3C     914
5862  KRTAP5-1     278

[309 rows x 2 columns]

In [110]:
relevant_ONLYHugoSymbols_ProteinLength_allTNandNONTN_Q1.isna().sum()

symbol    0
length    0
dtype: int64

In [111]:
# save the dataset 
os.chdir("C:/Users/Cristina/OneDrive/Documenti/BCG/Tesi/MutClust_input_definitivo")
relevant_ONLYHugoSymbols_ProteinLength_allTNandNONTN_Q1.to_csv("Symbol_ProteinLength_relevantONLYhugosymbols_TNandNONTN_Q1_definitivo.txt", index=False, sep='\t')