## MutClustSW dataset preparation - Only TNBC patients

18 hypermutated patients and 9 hypomutated patients are deleted

### 1. p-value < 0.05

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import os
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# load the total ductal mutation dataset with the corrected protein_positions end and start
os.chdir("C:/Users/Cristina/OneDrive/Documenti/BCG/Tesi")
total_ductal_dataset = pd.read_csv('data_mutation_total_ductal_nohypo_nohyper_CORRECTION_protein_pos_definitivo.csv', sep=None, engine='python')
total_ductal_dataset

,PATIENT_ID,Tumor_Sample_Barcode,Hugo_Symbol,Chromosome,Start_Position,End_Position,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Transcript_ID,Gene_length,ENSP,Hugo_variant,Mutation_length,Protein_position_start,Protein_position_end
0,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,KALRN,3,123988087.0,123988087.0,Missense_Mutation,SNP,G,G,C,ENST00000240874.3:c.948G>C,p.E316D,ENST00000240874,646303,NaN,KALRN_Missense_Mutation,1.0,316.0,316.0
1,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,ANK2,4,114195720.0,114195720.0,Missense_Mutation,SNP,C,C,T,ENST00000357077.4:c.1598C>T,p.P533L,ENST00000357077,565632,NaN,ANK2_Missense_Mutation,1.0,533.0,533.0
2,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,SORBS2,4,186539742.0,186539742.0,Missense_Mutation,SNP,G,G,C,ENST00000355634.5:c.2936C>G,p.S979C,ENST00000355634,371209,NaN,SORBS2_Missense_Mutation,1.0,979.0,979.0
3,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,PCDHA11,5,140250828.0,140250828.0,Missense_Mutation,SNP,C,C,G,ENST00000398640.2:c.2140C>G,p.L714V,ENST00000398640,143241,NaN,PCDHA11_Missense_Mutation,1.0,714.0,714.0
4,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,WRNIP1,6,2766210.0,2766210.0,Missense_Mutation,SNP,C,C,A,ENST00000380773.4:c.354C>A,p.S118R,ENST00000380773,21539,NaN,WRNIP1_Missense_Mutation,1.0,118.0,118.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139365,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,NRSN2,20,333991.0,333991.0,Silent,SNP,C,C,T,ENST00000382285.2:c.327C>T,p.N109=,ENST00000382285,12879,NaN,NRSN2_Silent,1.0,109.0,109.0
139366,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,CHRNA4,20,61986887.0,61986887.0,Intron,SNP,G,G,C,ENST00000370263.4:c.383+440C>G,p.*128*,ENST00000370263,34334,NaN,CHRNA4_Intron,1.0,NaN,NaN
139367,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,CHRNA4,20,61987386.0,61987386.0,Silent,SNP,G,G,A,ENST00000370263.4:c.324C>T,p.V108=,ENST00000370263,34334,NaN,CHRNA4_Silent,1.0,108.0,108.0
139368,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,KCNQ2,20,62078103.0,62078103.0,Silent,SNP,G,G,A,ENST00000359125.2:c.384C>T,p.I128=,ENST00000359125,66452,NaN,KCNQ2_Silent,1.0,128.0,128.0
139369,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,XBP1,22,29191563.0,29191563.0,Nonsense_Mutation,SNP,G,G,A,ENST00000216037.6:c.757C>T,p.Q253*,ENST00000216037,6043,NaN,XBP1_Nonsense_Mutation,1.0,253.0,253.0

**NOTE: in this dataset, hypomutated and hypermutated patients have already been deleted**

In [3]:
total_ductal_dataset.PATIENT_ID.nunique()

1527

In [4]:
total_ductal_dataset.Hugo_Symbol.nunique()

19466

In [5]:
# extract from the total ductal dataframe the unique Hugo Symbol genes 
unique_genes_total_ductal=total_ductal_dataset['Hugo_Symbol'].unique()
unique_genes_total_ductal=pd.DataFrame(unique_genes_total_ductal, columns=['Hugo_Symbol'])
unique_genes_total_ductal

         Hugo_Symbol
0              KALRN
1               ANK2
2             SORBS2
3            PCDHA11
4             WRNIP1
...              ...
19461          FGF17
19462          LYVE1
19463       C12orf29
19464          HSBP1
19465  MEF2BNB-MEF2B

[19466 rows x 1 columns]

In [6]:
# load the significant genes (only TN) with p-val < 0.05
os.chdir("C:/Users/Cristina/OneDrive/Documenti/BCG/Tesi/Significant genes_definitivo")
significant_genes_onlyTN_pval_005 = pd.read_csv('significant_genes_onlyTN_pval_005_definitivo.csv', sep=',', engine='python')
significant_genes_onlyTN_pval_005.rename(columns={"Genes": "Hugo_Symbol"}, inplace=True)
significant_genes_onlyTN_pval_005

    Hugo_Symbol
0          TP53
1           RB1
2        PIK3CA
3         FBXW7
4          PTEN
..          ...
362      MCF2L2
363      ADRBK2
364        SUCO
365        XRN1
366       G3BP1

[367 rows x 1 columns]

In [7]:
# study if there are gene names inconsistencies between relevant genes with p-val < 0.05 and total ductal genes 
pd.merge(significant_genes_onlyTN_pval_005, unique_genes_total_ductal, how='inner', on=['Hugo_Symbol'])

    Hugo_Symbol
0          TP53
1           RB1
2        PIK3CA
3         FBXW7
4          PTEN
..          ...
362      MCF2L2
363      ADRBK2
364        SUCO
365        XRN1
366       G3BP1

[367 rows x 1 columns]

There are not gene names' inconsistencies

In [8]:
significant_genes_onlyTN_pval_005_array = significant_genes_onlyTN_pval_005['Hugo_Symbol'].values
significant_genes_onlyTN_pval_005_array

array(['TP53', 'RB1', 'PIK3CA', 'FBXW7', 'PTEN', 'BRCA1', 'CDKN2A',
       'MYL10', 'ZKSCAN1', 'MGAT5B', 'MAML3', 'NOTCH2', 'NBN', 'STAB2',
       'RAB42', 'ATG4C', 'PIK3R1', 'C6orf118', 'LZTR1', 'MTMR12',
       'NUP153', 'COIL', 'ZNF195', 'PSKH1', 'CCRL2', 'CREBBP', 'NAA50',
       'AMZ1', 'CACNA1S', 'DDOST', 'C8orf31', 'MEFV', 'RC3H2', 'CDC20',
       'BAP1', 'NOD2', 'GP2', 'ZNF500', 'STK10', 'CTCF', 'CHRNB2',
       'TMPRSS13', 'FAM166B', 'GALNTL5', 'NPAS4', 'WBSCR27', 'STAG2',
       'ZMIZ1', 'FANCG', 'ARHGAP5', 'WDR62', 'USP8', 'GRPEL2', 'NDRG1',
       'LARP4B', 'GOLGA3', 'RDH5', 'TRIM14', 'USP9X', 'CEACAM3', 'KDM6A',
       'PDLIM4', 'SPPL3', 'LDLR', 'GPR97', 'SIN3B', 'PRB4', 'ADAM30',
       'TSKS', 'RBM47', 'NPEPPS', 'KMT2C', 'SMTNL1', 'NAGK', 'ERCC5',
       'SCAPER', 'TRPV5', 'SERPINA4', 'VPS9D1', 'KNG1', 'STAT1', 'FANK1',
       'LOR', 'TNRC6A', 'BMPR2', 'SETDB1', 'CACNA1F', 'CALB2', 'CRYBA1',
       'FLII', 'CYHR1', 'TANC1', 'COL6A6', 'TRAPPC10', 'TMED6', 'SLAMF9',
       'TFIP11', 'ATP11A', 'ASTN1', 'CCNE2', 'LAMP1', 'ASCC2', 'MMS22L',
       'ZNF341', 'ATG14', 'MFSD3', 'ADK', 'PRB3', 'ZNF311', 'SH3TC1',
       'COL24A1', 'DSC3', 'FAM65B', 'SP140', 'G6PD', 'AKT1', 'SESN2',
       'IP6K3', 'OR4X2', 'EPS8L3', 'AGT', 'UACA', 'COPG1', 'FILIP1L',
       'TFPI2', 'ZNF710', 'ZNF251', 'TCHHL1', 'APC', 'ARAP3', 'IFT172',
       'CCNDBP1', 'ANKRD11', 'BATF', 'PRUNE', 'ITGAM', 'NASP', 'TMEM14B',
       'EPAS1', 'AANAT', 'DNAL1', 'LSM2', 'DDB1', 'LEF1', 'ARHGAP24',
       'KLC3', 'ATRX', 'GPR119', 'CXorf23', 'SLC1A7', 'E2F7', 'AKIRIN1',
       'RASIP1', 'SCG3', 'MSH2', 'FYB', 'ASH2L', 'NPY4R', 'C16orf62',
       'ZNF764', 'HERC1', 'HRAS', 'HAUS8', 'HCRT', 'TMEM214', 'UBE3B',
       'TRIML2', 'RPL18A', 'FKBP2', 'BCL9', 'PTPRJ', 'DDX42', 'ETV3L',
       'POLE3', 'AIG1', 'TECR', 'CCDC53', 'RGN', 'C11orf85', 'ZNF608',
       'SERPINB3', 'DNAH10', 'PLOD1', 'WASF3', 'TRIM6', 'HNRNPUL1',
       'PTPRE', 'USPL1', 'NAV3', 'CCSER1', 'ETFB', 'CASZ1', 'THUMPD2',
       'AKT2', 'PHIP', 'MARC1', 'SETD6', 'DNTTIP2', 'PARP9', 'ASXL2',
       'SNAP23', 'GAS6', 'OCSTAMP', 'RPL18', 'BMP2', 'CCDC126', 'TULP4',
       'ARNTL2', 'KCNV2', 'NCCRP1', 'PPEF2', 'ZBTB24', 'ACTN4', 'OSR2',
       'GLS', 'NXPE3', 'DUSP18', 'PLEKHH2', 'ALPK1', 'KLHL40', 'APTX',
       'AMPD1', 'HERC4', 'TAAR5', 'SEMA5A', 'MTRF1', 'WFDC5', 'BATF2',
       'MTM1', 'MATN4', 'MBD6', 'MEA1', 'KIAA1586', 'KRTAP24-1', 'KCNH6',
       'SRPK1', 'FSD2', 'CPT1B', 'NCMAP', 'OMA1', 'KCNT2', 'KRTAP9-8',
       'LRRC37A3', 'NCF2', 'CSN2', 'MCHR1', 'C19orf10', 'LPCAT3', 'LCA5L',
       'RPS6', 'CPEB1', 'P2RY8', 'RNF220', 'ACSM5', 'DPP8', 'CLN3',
       'GRAMD1C', 'ACTG1', 'TACC3', 'STK31', 'TAS2R31', 'MUC4', 'CCDC57',
       'SMARCE1', 'PDCD4', 'UBAP1', 'AKAP4', 'RBPJL', 'ARPC5', 'AQR',
       'KIAA1324', 'ZNF438', 'FAH', 'MYH7B', 'C11orf35', 'CHI3L1', 'CMBL',
       'POGZ', 'TSC1', 'CD33', 'STRN4', 'MKNK2', 'OSBP2', 'CCNT2',
       'SERTAD3', 'FAM153A', 'GPR3', 'LRP4', 'UPF1', 'KIAA1614', 'OR2W3',
       'MUSK', 'LDOC1L', 'TRIM24', 'ACAN', 'PNMAL1', 'GPATCH4',
       'B4GALNT3', 'P2RX2', 'DIEXF', 'GPR144', 'NUP160', 'SELL', 'SPTAN1',
       'TNRC6C', 'COL6A3', 'MYOT', 'BCL10', 'GLUD2', 'ZC3HC1', 'DNMT3L',
       'LRRC16B', 'SERPINB4', 'PLA2G3', 'SLC11A2', 'KLF10', 'CRABP1',
       'KAT8', 'TYROBP', 'CCAR1', 'PI16', 'TSTA3', 'CFP', 'ERG', 'KATNB1',
       'DDX55', 'COL4A4', 'SEC24B', 'BRCA2', 'NDFIP2', 'PSTPIP2',
       'TRMT1L', 'PITX1', 'PCDHGB4', 'NBL1', 'SPP1', 'XPO5', 'MBOAT1',
       'SVIL', 'SOGA2', 'INPP5A', 'PUM1', 'MRPS7', 'LGALS14', 'WBP5',
       'VAMP1', 'ALK', 'ARID1A', 'TMEM126A', 'ITGAV', 'PPARG', 'SLC26A10',
       'TSPAN12', 'CD93', 'RHPN1', 'CATSPER1', 'SREBF1', 'KPRP',
       'GLIPR1L2', 'KIR3DL2', 'LPCAT2', 'CAST', 'MCF2L2', 'ADRBK2',
       'SUCO', 'XRN1', 'G3BP1'], dtype=object)

### Preparation of the dataset for MutClust

In [9]:
# select the total ductal mutations belonging to the relevant genes found by MutSig (p-value < 0.05)
data_mutation_SINIFICANTgenes_onlyTN_p_005= total_ductal_dataset[total_ductal_dataset['Hugo_Symbol'].isin(significant_genes_onlyTN_pval_005_array)].copy()
data_mutation_SINIFICANTgenes_onlyTN_p_005

,PATIENT_ID,Tumor_Sample_Barcode,Hugo_Symbol,Chromosome,Start_Position,End_Position,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Transcript_ID,Gene_length,ENSP,Hugo_variant,Mutation_length,Protein_position_start,Protein_position_end
15,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,TP53,17,7574003.0,7574003.0,Nonsense_Mutation,SNP,G,G,A,ENST00000269305.4:c.1024C>T,p.R342*,ENST00000269305,25760,NaN,TP53_Nonsense_Mutation,1.0,342.0,342.0
18,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,PIK3CA,3,178952150.0,178952151.0,Frame_Shift_Ins,INS,-,-,TTTT,ENST00000263967.3:c.3205_3206insTTTT,p.*1069Ffs*5,ENST00000263967,91980,NaN,PIK3CA_Frame_Shift_Ins,2.0,1069.0,1069.0
22,brca_smc_2018_BB01_004,brca_smc_2018_BB01_004,TP53,17,7577117.0,7577117.0,Missense_Mutation,SNP,A,A,C,ENST00000269305.4:c.821T>G,p.V274G,ENST00000269305,25760,NaN,TP53_Missense_Mutation,1.0,274.0,274.0
25,brca_smc_2018_BB01_004,brca_smc_2018_BB01_004,MAML3,4,140811082.0,140811083.0,In_Frame_Ins,INS,-,-,TGT,ENST00000509479.2:c.1508_1509insCAA,p.Q503delinsHK,ENST00000509479,437432,NaN,MAML3_In_Frame_Ins,2.0,503.0,503.0
33,brca_smc_2018_BB01_005,brca_smc_2018_BB01_005,COL6A6,3,130285953.0,130285953.0,Missense_Mutation,SNP,C,C,T,ENST00000358511.6:c.1690C>T,p.H564Y,ENST00000358511,117822,NaN,COL6A6_Missense_Mutation,1.0,564.0,564.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139207,MBCProject_ygcMFgCR,RP-1156_MBCProject_ygcMFgCR_T1A_v1_Exome,APC,5,112162816.0,112162816.0,Missense_Mutation,SNP,G,G,A,ENST00000257430.4:c.1420G>A,p.A474T,ENST00000257430,138742,NaN,APC_Missense_Mutation,1.0,474.0,474.0
139243,MBCProject_ygcMFgCR,RP-1156_MBCProject_ygcMFgCR_T1A_v1_Exome,SVIL,10,29762807.0,29762807.0,Missense_Mutation,SNP,G,G,A,ENST00000355867.4:c.5489C>T,p.A1830V,ENST00000355867,279444,NaN,SVIL_Missense_Mutation,1.0,1830.0,1830.0
139265,MBCProject_ygcMFgCR,RP-1156_MBCProject_ygcMFgCR_T1A_v1_Exome,ATP11A,13,113530150.0,113530150.0,Silent,SNP,C,C,T,ENST00000375645.3:c.3222C>T,p.P1074=,ENST00000375645,196840,NaN,ATP11A_Silent,1.0,1074.0,1074.0
139294,MBCProject_ygcMFgCR,RP-1156_MBCProject_ygcMFgCR_T1A_v1_Exome,SOGA2,18,8824961.0,8824961.0,Silent,SNP,C,C,G,ENST00000306329.11:c.4410C>G,p.P1470=,ENST00000306329,127118,NaN,SOGA2_Silent,1.0,1470.0,1470.0
139317,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,EPAS1,2,46525087.0,46525087.0,Intron,SNP,G,G,A,ENST00000263734.3:c.26+11G>A,p.*9*,ENST00000263734,93031,NaN,EPAS1_Intron,1.0,NaN,NaN

In [10]:
data_mutation_SINIFICANTgenes_onlyTN_p_005.PATIENT_ID.nunique()

1404

123 (1527-1404) ductal patients do not carry mutations on the significant genes with p-value < 0.05 selected by MutSig2CV

In [11]:
data_mutation_SINIFICANTgenes_onlyTN_p_005.Hugo_Symbol.nunique()

367

In [12]:
# look at the number of missing values in the dataframe 
data_mutation_SINIFICANTgenes_onlyTN_p_005.isna().sum()

PATIENT_ID                   0
Tumor_Sample_Barcode         0
Hugo_Symbol                  0
Chromosome                   0
Start_Position               0
End_Position                 0
Variant_Classification       0
Variant_Type                 0
Reference_Allele             0
Tumor_Seq_Allele1            0
Tumor_Seq_Allele2            0
HGVSc                       83
HGVSp_Short                102
Transcript_ID             2861
Gene_length                  0
ENSP                      3543
Hugo_variant                 0
Mutation_length              0
Protein_position_start     332
Protein_position_end       332
dtype: int64

3543 ENSP values are missing.

In [13]:
data_mutation_SINIFICANTgenes_onlyTN_P005_protein_pos = data_mutation_SINIFICANTgenes_onlyTN_p_005[['Protein_position_start']].copy()
data_mutation_SINIFICANTgenes_onlyTN_P005_protein_pos

        Protein_position_start
15                       342.0
18                      1069.0
22                       274.0
25                       503.0
33                       564.0
...                        ...
139207                   474.0
139243                  1830.0
139265                  1074.0
139294                  1470.0
139317                     NaN

[5825 rows x 1 columns]

In [14]:
data_mutation_SINIFICANTgenes_onlyTN_p_005['Protein_position_start'] = pd.to_numeric(data_mutation_SINIFICANTgenes_onlyTN_p_005['Protein_position_start']).copy()

In [15]:
# let's focus on the two columns Hugo Symbol and ENSP
data_mutation_SINIFICANTgenes_onlyTN_P005_gene_ENSP = data_mutation_SINIFICANTgenes_onlyTN_p_005[['Hugo_Symbol', 'ENSP']].copy()
data_mutation_SINIFICANTgenes_onlyTN_P005_gene_ENSP

       Hugo_Symbol ENSP
15            TP53  NaN
18          PIK3CA  NaN
22            TP53  NaN
25           MAML3  NaN
33          COL6A6  NaN
...            ...  ...
139207         APC  NaN
139243        SVIL  NaN
139265      ATP11A  NaN
139294       SOGA2  NaN
139317       EPAS1  NaN

[5825 rows x 2 columns]

In [16]:
# sostituisci i missing values nella colonna ENSP con la parola 'VUOTO'
def sostituzione_nan (df_relevant_genes_HS_ENSP):

    for index, row in df_relevant_genes_HS_ENSP.iterrows():
        gene = row.Hugo_Symbol
        ENSP =  str(row.ENSP)
    #print(type(ENSP))
        if ENSP.startswith('ENSP') is False:
            df_relevant_genes_HS_ENSP.loc[index, 'ENSP'] = 'VUOTO' # se non c'è l'ENSP della proteina metti 'VUOTO'
            #count_nan = count_nan+1
    return (df_relevant_genes_HS_ENSP)

In [17]:
# substitute the ENSP NaN with 'VUOTO'
data_mutation_SINIFICANTgenes_onlyTN_P005_gene_ENSP_nonan = sostituzione_nan(data_mutation_SINIFICANTgenes_onlyTN_P005_gene_ENSP)
data_mutation_SINIFICANTgenes_onlyTN_P005_gene_ENSP_nonan

       Hugo_Symbol   ENSP
15            TP53  VUOTO
18          PIK3CA  VUOTO
22            TP53  VUOTO
25           MAML3  VUOTO
33          COL6A6  VUOTO
...            ...    ...
139207         APC  VUOTO
139243        SVIL  VUOTO
139265      ATP11A  VUOTO
139294       SOGA2  VUOTO
139317       EPAS1  VUOTO

[5825 rows x 2 columns]

In [18]:
(data_mutation_SINIFICANTgenes_onlyTN_P005_gene_ENSP_nonan['ENSP']=='VUOTO').sum()

3543

In [19]:
## The function Vett_transcript takes all the unique Hugo Symbols as indexes and create the column 'Protein length' filled with zeros 
def Index_relevant_genes (df_mut):
    vett_Hugo_symbols_relevant = df_mut.Hugo_Symbol.unique()
    df_vett_Hugo_symbols_relevant = pd.DataFrame(index = vett_Hugo_symbols_relevant, columns = ['Protein_length'])
    df_vett_Hugo_symbols_relevant = df_vett_Hugo_symbols_relevant.fillna(0)
    return (df_vett_Hugo_symbols_relevant)

In [20]:
Hugo_symbols_relevant_SIGNIFICANT_genes_onlyTN_P005 = Index_relevant_genes(data_mutation_SINIFICANTgenes_onlyTN_P005_gene_ENSP_nonan)
Hugo_symbols_relevant_SIGNIFICANT_genes_onlyTN_P005

         Protein_length
TP53                  0
PIK3CA                0
MAML3                 0
COL6A6                0
ATP11A                0
...                 ...
PSTPIP2               0
LSM2                  0
HCRT                  0
CCNT2                 0
CSN2                  0

[367 rows x 1 columns]

### Retrieve the protein length using pyensembl

In [21]:
from pyensembl import EnsemblRelease

data = EnsemblRelease(75)

def protein_length_computation(vett_relevant_genes, df_relevant_genes_HS_ENSP_nonan):
    
    for index, row in vett_relevant_genes.iterrows():
        gene = index
        length = row.Protein_length
        if length == 0:
            df = df_relevant_genes_HS_ENSP_nonan[df_relevant_genes_HS_ENSP_nonan['Hugo_Symbol'] == gene]
            for index, row in df.iterrows():
                ENSP_singolo = row.ENSP
                if ENSP_singolo != 'VUOTO':
                #print(ENSP_singolo)
                    protein = data.protein_sequence(ENSP_singolo)
                    protein_length = len(protein)
                    vett_relevant_genes.loc[gene, 'Protein_length'] = protein_length

In [22]:
protein_length_computation(Hugo_symbols_relevant_SIGNIFICANT_genes_onlyTN_P005, data_mutation_SINIFICANTgenes_onlyTN_P005_gene_ENSP_nonan)

INFO:pyensembl.sequence_data:Loaded sequence dictionary from C:\Users\Cristina\AppData\Local\pyensembl\GRCh37\ensembl75\pyensembl\GRCh37\ensembl75\Cache\Homo_sapiens.GRCh37.75.pep.all.fa.gz.pickle

In [23]:
Hugo_symbols_relevant_SIGNIFICANT_genes_onlyTN_P005

         Protein_length
TP53                393
PIK3CA             1068
MAML3              1138
COL6A6             2263
ATP11A             1134
...                 ...
PSTPIP2             334
LSM2                 95
HCRT                  0
CCNT2                 0
CSN2                  0

[367 rows x 1 columns]

In [24]:
Hugo_symbols_relevant_SIGNIFICANT_genes_onlyTN_P005.loc[Hugo_symbols_relevant_SIGNIFICANT_genes_onlyTN_P005['Protein_length']== 0]

          Protein_length
CDKN2A                 0
KRTAP9-8               0
LOR                    0
NBL1                   0
TYROBP                 0
HCRT                   0
CCNT2                  0
CSN2                   0

In [25]:
Hugo_symbols_relevant_SIGNIFICANT_genes_onlyTN_P005.loc['CDKN2A','Protein_length'] = 156

In [26]:
Hugo_symbols_relevant_SIGNIFICANT_genes_onlyTN_P005.loc['NBL1','Protein_length'] = 181

In [27]:
Hugo_symbols_relevant_SIGNIFICANT_genes_onlyTN_P005.loc['KRTAP9-8','Protein_length'] = 159

In [28]:
Hugo_symbols_relevant_SIGNIFICANT_genes_onlyTN_P005.loc['LOR','Protein_length'] = 312

In [29]:
Hugo_symbols_relevant_SIGNIFICANT_genes_onlyTN_P005.loc['HCRT','Protein_length'] = 131

In [30]:
Hugo_symbols_relevant_SIGNIFICANT_genes_onlyTN_P005.loc['CCNT2','Protein_length'] = 730

In [31]:
Hugo_symbols_relevant_SIGNIFICANT_genes_onlyTN_P005.loc['CSN2','Protein_length'] = 226

In [32]:
Hugo_symbols_relevant_SIGNIFICANT_genes_onlyTN_P005.loc['TYROBP','Protein_length'] = 113

In [33]:
Hugo_symbols_relevant_SIGNIFICANT_genes_onlyTN_P005.loc[Hugo_symbols_relevant_SIGNIFICANT_genes_onlyTN_P005['Protein_length']== 0]

Empty DataFrame
Columns: [Protein_length]
Index: []

In [34]:
data_mutation_SINIFICANTgenes_onlyTN_p_005['Protein_position_start'].isna().sum()

332

In [35]:
# Define a function that takes in input the mutation dataset containing only the relevant genes and gives in output a new df containing HugoSymbol e Protein Position
def protein_position_Hugo_Symbol_only(relevant_mutations):
    df_positions = []

    for index, row in relevant_mutations.iterrows():
        df_positions.append([row.Hugo_Symbol, row.Protein_position_start])
    
    df_positions = pd.DataFrame(df_positions, columns = ['symbol', 'position'])
    df_positions = df_positions.dropna() # drop the protein position missing values 
    
    # Convert single column to int dtype
    df_positions['position'] = pd.to_numeric(df_positions['position'])
    df_positions = df_positions.astype({"position":"int"})
    
    return (df_positions)

In [36]:
protein_position_hugoSymbols_onlyTN_P005 = protein_position_Hugo_Symbol_only(data_mutation_SINIFICANTgenes_onlyTN_p_005)
protein_position_hugoSymbols_onlyTN_P005

      symbol  position
0       TP53       342
1     PIK3CA      1069
2       TP53       274
3      MAML3       503
4     COL6A6       564
...      ...       ...
5819  TRMT1L       124
5820     APC       474
5821    SVIL      1830
5822  ATP11A      1074
5823   SOGA2      1470

[5493 rows x 2 columns]

In [37]:
# save the dataset 
os.chdir("C:/Users/Cristina/OneDrive/Documenti/BCG/Tesi/MutClust_input_definitivo")
protein_position_hugoSymbols_onlyTN_P005.to_csv("Symbol_ProteinPosition_onlyHugoSymbol_onlyTN_pval005_definitivo.txt", index=False, sep='\t')

In [38]:
Hugo_symbols_relevant_SIGNIFICANT_genes_onlyTN_P005

         Protein_length
TP53                393
PIK3CA             1068
MAML3              1138
COL6A6             2263
ATP11A             1134
...                 ...
PSTPIP2             334
LSM2                 95
HCRT                131
CCNT2               730
CSN2                226

[367 rows x 1 columns]

In [39]:
# add the Protein_length column to the relevant mutation dataset 
Hugo_symbols_relevant_SIGNIFICANT_genes_onlyTN_P005.reset_index(level=0, inplace=True)
Hugo_symbols_relevant_SIGNIFICANT_genes_onlyTN_P005.rename(columns={"index": "Hugo_Symbol"}, inplace=True)
Hugo_symbols_relevant_SIGNIFICANT_genes_onlyTN_P005

    Hugo_Symbol  Protein_length
0          TP53             393
1        PIK3CA            1068
2         MAML3            1138
3        COL6A6            2263
4        ATP11A            1134
..          ...             ...
362     PSTPIP2             334
363        LSM2              95
364        HCRT             131
365       CCNT2             730
366        CSN2             226

[367 rows x 2 columns]

In [40]:
# add the protein lengths to the mutation dataset 
data_mutation_SINIFICANTgenes_onlyTN_p_005 = data_mutation_SINIFICANTgenes_onlyTN_p_005.join(Hugo_symbols_relevant_SIGNIFICANT_genes_onlyTN_P005.set_index('Hugo_Symbol'), on='Hugo_Symbol')
data_mutation_SINIFICANTgenes_onlyTN_p_005

,PATIENT_ID,Tumor_Sample_Barcode,Hugo_Symbol,Chromosome,Start_Position,End_Position,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,...,HGVSc,HGVSp_Short,Transcript_ID,Gene_length,ENSP,Hugo_variant,Mutation_length,Protein_position_start,Protein_position_end,Protein_length
15,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,TP53,17,7574003.0,7574003.0,Nonsense_Mutation,SNP,G,G,...,ENST00000269305.4:c.1024C>T,p.R342*,ENST00000269305,25760,NaN,TP53_Nonsense_Mutation,1.0,342.0,342.0,393
18,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,PIK3CA,3,178952150.0,178952151.0,Frame_Shift_Ins,INS,-,-,...,ENST00000263967.3:c.3205_3206insTTTT,p.*1069Ffs*5,ENST00000263967,91980,NaN,PIK3CA_Frame_Shift_Ins,2.0,1069.0,1069.0,1068
22,brca_smc_2018_BB01_004,brca_smc_2018_BB01_004,TP53,17,7577117.0,7577117.0,Missense_Mutation,SNP,A,A,...,ENST00000269305.4:c.821T>G,p.V274G,ENST00000269305,25760,NaN,TP53_Missense_Mutation,1.0,274.0,274.0,393
25,brca_smc_2018_BB01_004,brca_smc_2018_BB01_004,MAML3,4,140811082.0,140811083.0,In_Frame_Ins,INS,-,-,...,ENST00000509479.2:c.1508_1509insCAA,p.Q503delinsHK,ENST00000509479,437432,NaN,MAML3_In_Frame_Ins,2.0,503.0,503.0,1138
33,brca_smc_2018_BB01_005,brca_smc_2018_BB01_005,COL6A6,3,130285953.0,130285953.0,Missense_Mutation,SNP,C,C,...,ENST00000358511.6:c.1690C>T,p.H564Y,ENST00000358511,117822,NaN,COL6A6_Missense_Mutation,1.0,564.0,564.0,2263
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139207,MBCProject_ygcMFgCR,RP-1156_MBCProject_ygcMFgCR_T1A_v1_Exome,APC,5,112162816.0,112162816.0,Missense_Mutation,SNP,G,G,...,ENST00000257430.4:c.1420G>A,p.A474T,ENST00000257430,138742,NaN,APC_Missense_Mutation,1.0,474.0,474.0,2843
139243,MBCProject_ygcMFgCR,RP-1156_MBCProject_ygcMFgCR_T1A_v1_Exome,SVIL,10,29762807.0,29762807.0,Missense_Mutation,SNP,G,G,...,ENST00000355867.4:c.5489C>T,p.A1830V,ENST00000355867,279444,NaN,SVIL_Missense_Mutation,1.0,1830.0,1830.0,2214
139265,MBCProject_ygcMFgCR,RP-1156_MBCProject_ygcMFgCR_T1A_v1_Exome,ATP11A,13,113530150.0,113530150.0,Silent,SNP,C,C,...,ENST00000375645.3:c.3222C>T,p.P1074=,ENST00000375645,196840,NaN,ATP11A_Silent,1.0,1074.0,1074.0,1134
139294,MBCProject_ygcMFgCR,RP-1156_MBCProject_ygcMFgCR_T1A_v1_Exome,SOGA2,18,8824961.0,8824961.0,Silent,SNP,C,C,...,ENST00000306329.11:c.4410C>G,p.P1470=,ENST00000306329,127118,NaN,SOGA2_Silent,1.0,1470.0,1470.0,1586
139317,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,EPAS1,2,46525087.0,46525087.0,Intron,SNP,G,G,...,ENST00000263734.3:c.26+11G>A,p.*9*,ENST00000263734,93031,NaN,EPAS1_Intron,1.0,NaN,NaN,870

In [41]:
# save the dataset 
os.chdir("C:/Users/Cristina/OneDrive/Documenti/BCG/Tesi/MutClust_input_definitivo")
data_mutation_SINIFICANTgenes_onlyTN_p_005.to_csv("data_mutation_SINIFICANTgenes_ONLYhugo_onlyTN_P005_definitivo.txt", index=False, sep='\t')

In [42]:
data_mutation_SINIFICANTgenes_onlyTN_p_005.Variant_Classification.nunique()

16

In [43]:
data_mutation_SINIFICANTgenes_onlyTN_p_005.Variant_Classification.unique()

array(['Nonsense_Mutation', 'Frame_Shift_Ins', 'Missense_Mutation',
       'In_Frame_Ins', 'Splice_Site', 'Frame_Shift_Del', 'In_Frame_Del',
       'Silent', 'Intron', 'Nonstop_Mutation', 'Splice_Region', "5'Flank",
       "3'UTR", "5'UTR", "3'Flank", 'Translation_Start_Site'],
      dtype=object)

In [44]:
# Define a function that gives in output a new df containing HugoSymbol e Protein Length
def protein_length_only_Hugo_Symbol(relevant_mutations):  
    df_protein_lengths = []
    

    for index, row in relevant_mutations.iterrows():
        df_protein_lengths.append([row.Hugo_Symbol, row.Protein_length])
    
    df_protein_lengths = pd.DataFrame(df_protein_lengths, columns = ['symbol', 'length'])
    df_protein_lengths = df_protein_lengths.dropna()
    df_protein_lengths =  df_protein_lengths.drop_duplicates()
    
    return (df_protein_lengths)

In [45]:
relevant_ONLYHugoSymbols_ProteinLength_onlyTN_P005 = protein_length_only_Hugo_Symbol(data_mutation_SINIFICANTgenes_onlyTN_p_005)
relevant_ONLYHugoSymbols_ProteinLength_onlyTN_P005

       symbol  length
0        TP53     393
1      PIK3CA    1068
3       MAML3    1138
4      COL6A6    2263
7      ATP11A    1134
...       ...     ...
3889  PSTPIP2     334
4206     LSM2      95
4354     HCRT     131
4854    CCNT2     730
5087     CSN2     226

[367 rows x 2 columns]

In [46]:
relevant_ONLYHugoSymbols_ProteinLength_onlyTN_P005.isna().sum()

symbol    0
length    0
dtype: int64

In [47]:
# save the dataset 
os.chdir("C:/Users/Cristina/OneDrive/Documenti/BCG/Tesi/MutClust_input_definitivo")
relevant_ONLYHugoSymbols_ProteinLength_onlyTN_P005.to_csv("Symbol_ProteinLength_relevantONLYhugosymbols_onlyTN_p005_definitivo.txt", index=False, sep='\t')

### 2. q-value < 1

In [48]:
total_ductal_dataset

,PATIENT_ID,Tumor_Sample_Barcode,Hugo_Symbol,Chromosome,Start_Position,End_Position,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Transcript_ID,Gene_length,ENSP,Hugo_variant,Mutation_length,Protein_position_start,Protein_position_end
0,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,KALRN,3,123988087.0,123988087.0,Missense_Mutation,SNP,G,G,C,ENST00000240874.3:c.948G>C,p.E316D,ENST00000240874,646303,NaN,KALRN_Missense_Mutation,1.0,316.0,316.0
1,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,ANK2,4,114195720.0,114195720.0,Missense_Mutation,SNP,C,C,T,ENST00000357077.4:c.1598C>T,p.P533L,ENST00000357077,565632,NaN,ANK2_Missense_Mutation,1.0,533.0,533.0
2,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,SORBS2,4,186539742.0,186539742.0,Missense_Mutation,SNP,G,G,C,ENST00000355634.5:c.2936C>G,p.S979C,ENST00000355634,371209,NaN,SORBS2_Missense_Mutation,1.0,979.0,979.0
3,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,PCDHA11,5,140250828.0,140250828.0,Missense_Mutation,SNP,C,C,G,ENST00000398640.2:c.2140C>G,p.L714V,ENST00000398640,143241,NaN,PCDHA11_Missense_Mutation,1.0,714.0,714.0
4,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,WRNIP1,6,2766210.0,2766210.0,Missense_Mutation,SNP,C,C,A,ENST00000380773.4:c.354C>A,p.S118R,ENST00000380773,21539,NaN,WRNIP1_Missense_Mutation,1.0,118.0,118.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139365,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,NRSN2,20,333991.0,333991.0,Silent,SNP,C,C,T,ENST00000382285.2:c.327C>T,p.N109=,ENST00000382285,12879,NaN,NRSN2_Silent,1.0,109.0,109.0
139366,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,CHRNA4,20,61986887.0,61986887.0,Intron,SNP,G,G,C,ENST00000370263.4:c.383+440C>G,p.*128*,ENST00000370263,34334,NaN,CHRNA4_Intron,1.0,NaN,NaN
139367,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,CHRNA4,20,61987386.0,61987386.0,Silent,SNP,G,G,A,ENST00000370263.4:c.324C>T,p.V108=,ENST00000370263,34334,NaN,CHRNA4_Silent,1.0,108.0,108.0
139368,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,KCNQ2,20,62078103.0,62078103.0,Silent,SNP,G,G,A,ENST00000359125.2:c.384C>T,p.I128=,ENST00000359125,66452,NaN,KCNQ2_Silent,1.0,128.0,128.0
139369,MBCProject_zyt5TKFB,MBC-MBCProject_zyt5TKFB-Tumor-SM-CGM59,XBP1,22,29191563.0,29191563.0,Nonsense_Mutation,SNP,G,G,A,ENST00000216037.6:c.757C>T,p.Q253*,ENST00000216037,6043,NaN,XBP1_Nonsense_Mutation,1.0,253.0,253.0

In [49]:
# load the significant genes (only TN) with q-val < 1
os.chdir("C:/Users/Cristina/OneDrive/Documenti/BCG/Tesi/Significant genes_definitivo")
significant_genes_onlyTN_qval_1 = pd.read_csv('significant_genes_onlyTN_qval_1_definitivo.csv', sep=',', engine='python')
significant_genes_onlyTN_qval_1

   Hugo_Symbol
0         TP53
1          RB1
2       PIK3CA
3        FBXW7
4         PTEN
5        BRCA1
6       CDKN2A
7        MYL10
8      ZKSCAN1
9       MGAT5B
10       MAML3
11      NOTCH2
12         NBN
13       STAB2
14       RAB42
15       ATG4C
16      PIK3R1
17    C6orf118
18       LZTR1
19      MTMR12
20      NUP153
21        COIL
22      ZNF195

In [50]:
len(significant_genes_onlyTN_qval_1)

23

In [51]:
# study if there are gene names inconsistencies between relevant genes with q-val < 1 and total ductal genes 
pd.merge(significant_genes_onlyTN_qval_1, unique_genes_total_ductal, how='inner', on=['Hugo_Symbol'])

   Hugo_Symbol
0         TP53
1          RB1
2       PIK3CA
3        FBXW7
4         PTEN
5        BRCA1
6       CDKN2A
7        MYL10
8      ZKSCAN1
9       MGAT5B
10       MAML3
11      NOTCH2
12         NBN
13       STAB2
14       RAB42
15       ATG4C
16      PIK3R1
17    C6orf118
18       LZTR1
19      MTMR12
20      NUP153
21        COIL
22      ZNF195

There are not gene names' inconsistencies

In [52]:
significant_genes_onlyTN_qval_1_array = significant_genes_onlyTN_qval_1['Hugo_Symbol'].values
significant_genes_onlyTN_qval_1_array

array(['TP53', 'RB1', 'PIK3CA', 'FBXW7', 'PTEN', 'BRCA1', 'CDKN2A',
       'MYL10', 'ZKSCAN1', 'MGAT5B', 'MAML3', 'NOTCH2', 'NBN', 'STAB2',
       'RAB42', 'ATG4C', 'PIK3R1', 'C6orf118', 'LZTR1', 'MTMR12',
       'NUP153', 'COIL', 'ZNF195'], dtype=object)

In [53]:
len(significant_genes_onlyTN_qval_1_array)

23

### Preparation of the dataset for MutClust

In [54]:
# select the total ductal mutations belonging to the relevant genes found by MutSig (p-value < 0.05)
data_mutation_SINIFICANTgenes_onlyTN_q_1= total_ductal_dataset[total_ductal_dataset['Hugo_Symbol'].isin(significant_genes_onlyTN_qval_1_array)]
data_mutation_SINIFICANTgenes_onlyTN_q_1

,PATIENT_ID,Tumor_Sample_Barcode,Hugo_Symbol,Chromosome,Start_Position,End_Position,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Transcript_ID,Gene_length,ENSP,Hugo_variant,Mutation_length,Protein_position_start,Protein_position_end
15,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,TP53,17,7574003.0,7574003.0,Nonsense_Mutation,SNP,G,G,A,ENST00000269305.4:c.1024C>T,p.R342*,ENST00000269305,25760,NaN,TP53_Nonsense_Mutation,1.0,342.0,342.0
18,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,PIK3CA,3,178952150.0,178952151.0,Frame_Shift_Ins,INS,-,-,TTTT,ENST00000263967.3:c.3205_3206insTTTT,p.*1069Ffs*5,ENST00000263967,91980,NaN,PIK3CA_Frame_Shift_Ins,2.0,1069.0,1069.0
22,brca_smc_2018_BB01_004,brca_smc_2018_BB01_004,TP53,17,7577117.0,7577117.0,Missense_Mutation,SNP,A,A,C,ENST00000269305.4:c.821T>G,p.V274G,ENST00000269305,25760,NaN,TP53_Missense_Mutation,1.0,274.0,274.0
25,brca_smc_2018_BB01_004,brca_smc_2018_BB01_004,MAML3,4,140811082.0,140811083.0,In_Frame_Ins,INS,-,-,TGT,ENST00000509479.2:c.1508_1509insCAA,p.Q503delinsHK,ENST00000509479,437432,NaN,MAML3_In_Frame_Ins,2.0,503.0,503.0
34,brca_smc_2018_BB01_005,brca_smc_2018_BB01_005,PIK3CA,3,178952085.0,178952085.0,Missense_Mutation,SNP,A,A,G,ENST00000263967.3:c.3140A>G,p.H1047R,ENST00000263967,91980,NaN,PIK3CA_Missense_Mutation,1.0,1047.0,1047.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138181,MBCProject_pyhbI1H5,MBC-MBCProject_pyhbI1H5-Tumor-SM-GQCX6,TP53,17,7579356.0,7579356.0,Missense_Mutation,SNP,G,G,C,ENST00000269305.4:c.331C>G,p.L111V,ENST00000269305,25760,NaN,TP53_Missense_Mutation,1.0,111.0,111.0
138413,MBCProject_rJHBiKTl,MBC-MBCProject_rJHBiKTl-Tumor-SM-DL3K3,TP53,17,7578271.0,7578271.0,Missense_Mutation,SNP,T,T,C,ENST00000269305.4:c.578A>G,p.H193R,ENST00000269305,25760,NaN,TP53_Missense_Mutation,1.0,193.0,193.0
138591,MBCProject_rYSXcxcV,RP-1156_MBCProject_rYSXcxcV_T1_v4_Exome,TP53,17,7578208.0,7578208.0,Missense_Mutation,SNP,T,T,C,ENST00000269305.4:c.641A>G,p.H214R,ENST00000269305,25760,NaN,TP53_Missense_Mutation,1.0,214.0,214.0
138717,MBCProject_rvULI3TV,MBC-MBCProject_rvULI3TV-Tumor-SM-DL41F,ZKSCAN1,7,99630937.0,99630938.0,Frame_Shift_Ins,INS,-,-,C,ENST00000324306.6:c.810dup,p.R271Qfs*3,ENST00000324306,26109,NaN,ZKSCAN1_Frame_Shift_Ins,2.0,270.0,270.0
138871,MBCProject_xBfJfri9,MBC-MBCProject_xBfJfri9-Tumor-SM-CGLAP,PTEN,10,89720799.0,89720802.0,Frame_Shift_Del,DEL,TACT,TACT,-,ENST00000371953.3:c.955_958del,p.T319*,ENST00000371953,108818,NaN,PTEN_Frame_Shift_Del,4.0,317.0,317.0

In [55]:
data_mutation_SINIFICANTgenes_onlyTN_q_1.PATIENT_ID.nunique()

1058

469 (1527-1058) ductal patients do not carry mutations on the significant genes with q-value < 1 selected by MutSig2CV

In [56]:
data_mutation_SINIFICANTgenes_onlyTN_q_1.Hugo_Symbol.nunique()

23

In [57]:
# look at the number of missing values in the dataframe 
data_mutation_SINIFICANTgenes_onlyTN_q_1.isna().sum()

PATIENT_ID                   0
Tumor_Sample_Barcode         0
Hugo_Symbol                  0
Chromosome                   0
Start_Position               0
End_Position                 0
Variant_Classification       0
Variant_Type                 0
Reference_Allele             0
Tumor_Seq_Allele1            0
Tumor_Seq_Allele2            0
HGVSc                        5
HGVSp_Short                 12
Transcript_ID              802
Gene_length                  0
ENSP                      1438
Hugo_variant                 0
Mutation_length              0
Protein_position_start      48
Protein_position_end        48
dtype: int64

1438 ENSP values are missing.

In [58]:
data_mutation_SINIFICANTgenes_onlyTN_Q1_protein_pos = data_mutation_SINIFICANTgenes_onlyTN_q_1[['Protein_position_start']].copy()
data_mutation_SINIFICANTgenes_onlyTN_Q1_protein_pos

        Protein_position_start
15                       342.0
18                      1069.0
22                       274.0
25                       503.0
34                      1047.0
...                        ...
138181                   111.0
138413                   193.0
138591                   214.0
138717                   270.0
138871                   317.0

[1660 rows x 1 columns]

In [59]:
data_mutation_SINIFICANTgenes_onlyTN_Q1_protein_pos['Protein_position_start'] = pd.to_numeric(data_mutation_SINIFICANTgenes_onlyTN_Q1_protein_pos['Protein_position_start'])

In [60]:
# let's focus on the two columns Hugo Symbol and ENSP
data_mutation_SINIFICANTgenes_onlyTN_Q1_gene_ENSP = data_mutation_SINIFICANTgenes_onlyTN_q_1[['Hugo_Symbol', 'ENSP']].copy()
data_mutation_SINIFICANTgenes_onlyTN_Q1_gene_ENSP

       Hugo_Symbol ENSP
15            TP53  NaN
18          PIK3CA  NaN
22            TP53  NaN
25           MAML3  NaN
34          PIK3CA  NaN
...            ...  ...
138181        TP53  NaN
138413        TP53  NaN
138591        TP53  NaN
138717     ZKSCAN1  NaN
138871        PTEN  NaN

[1660 rows x 2 columns]

In [61]:
# substitute the ENSP NaN with 'VUOTO'
data_mutation_SINIFICANTgenes_onlyTN_Q1_gene_ENSP_nonan = sostituzione_nan(data_mutation_SINIFICANTgenes_onlyTN_Q1_gene_ENSP)
data_mutation_SINIFICANTgenes_onlyTN_Q1_gene_ENSP_nonan

       Hugo_Symbol   ENSP
15            TP53  VUOTO
18          PIK3CA  VUOTO
22            TP53  VUOTO
25           MAML3  VUOTO
34          PIK3CA  VUOTO
...            ...    ...
138181        TP53  VUOTO
138413        TP53  VUOTO
138591        TP53  VUOTO
138717     ZKSCAN1  VUOTO
138871        PTEN  VUOTO

[1660 rows x 2 columns]

In [62]:
(data_mutation_SINIFICANTgenes_onlyTN_Q1_gene_ENSP_nonan['ENSP']=='VUOTO').sum()

1438

In [63]:
Hugo_symbols_relevant_SIGNIFICANT_genes_onlyTN_Q1 = Index_relevant_genes(data_mutation_SINIFICANTgenes_onlyTN_Q1_gene_ENSP_nonan)
Hugo_symbols_relevant_SIGNIFICANT_genes_onlyTN_Q1

          Protein_length
TP53                   0
PIK3CA                 0
MAML3                  0
PTEN                   0
NOTCH2                 0
CDKN2A                 0
FBXW7                  0
RB1                    0
ZNF195                 0
PIK3R1                 0
C6orf118               0
STAB2                  0
BRCA1                  0
MGAT5B                 0
MYL10                  0
NUP153                 0
LZTR1                  0
MTMR12                 0
ZKSCAN1                0
COIL                   0
NBN                    0
ATG4C                  0
RAB42                  0

### Retrieve the protein length using pyensembl

In [64]:
protein_length_computation(Hugo_symbols_relevant_SIGNIFICANT_genes_onlyTN_Q1, data_mutation_SINIFICANTgenes_onlyTN_Q1_gene_ENSP_nonan)

In [65]:
Hugo_symbols_relevant_SIGNIFICANT_genes_onlyTN_Q1

          Protein_length
TP53                 393
PIK3CA              1068
MAML3               1138
PTEN                 403
NOTCH2              2471
CDKN2A                 0
FBXW7                707
RB1                  928
ZNF195               629
PIK3R1               724
C6orf118             469
STAB2               2551
BRCA1               1884
MGAT5B               801
MYL10                226
NUP153              1475
LZTR1                840
MTMR12               747
ZKSCAN1              563
COIL                 576
NBN                  754
ATG4C                458
RAB42                105

In [66]:
Hugo_symbols_relevant_SIGNIFICANT_genes_onlyTN_Q1.loc[Hugo_symbols_relevant_SIGNIFICANT_genes_onlyTN_Q1['Protein_length']== 0]

        Protein_length
CDKN2A               0

In [67]:
Hugo_symbols_relevant_SIGNIFICANT_genes_onlyTN_Q1.loc['CDKN2A','Protein_length'] = 156

In [68]:
Hugo_symbols_relevant_SIGNIFICANT_genes_onlyTN_Q1

          Protein_length
TP53                 393
PIK3CA              1068
MAML3               1138
PTEN                 403
NOTCH2              2471
CDKN2A               156
FBXW7                707
RB1                  928
ZNF195               629
PIK3R1               724
C6orf118             469
STAB2               2551
BRCA1               1884
MGAT5B               801
MYL10                226
NUP153              1475
LZTR1                840
MTMR12               747
ZKSCAN1              563
COIL                 576
NBN                  754
ATG4C                458
RAB42                105

In [69]:
data_mutation_SINIFICANTgenes_onlyTN_q_1['Protein_position_start'].isna().sum()

48

In [70]:
protein_position_hugoSymbols_onlyTN_Q1 = protein_position_Hugo_Symbol_only(data_mutation_SINIFICANTgenes_onlyTN_q_1)
protein_position_hugoSymbols_onlyTN_Q1

       symbol  position
0        TP53       342
1      PIK3CA      1069
2        TP53       274
3       MAML3       503
4      PIK3CA      1047
...       ...       ...
1655     TP53       111
1656     TP53       193
1657     TP53       214
1658  ZKSCAN1       270
1659     PTEN       317

[1612 rows x 2 columns]

In [72]:
# save the dataset 
os.chdir("C:/Users/Cristina/OneDrive/Documenti/BCG/Tesi/MutClust_input_definitivo")
protein_position_hugoSymbols_onlyTN_Q1.to_csv("Symbol_ProteinPosition_onlyHugoSymbol_onlyTN_qval1_definitivo.txt", index=False, sep='\t')

In [73]:
Hugo_symbols_relevant_SIGNIFICANT_genes_onlyTN_Q1

          Protein_length
TP53                 393
PIK3CA              1068
MAML3               1138
PTEN                 403
NOTCH2              2471
CDKN2A               156
FBXW7                707
RB1                  928
ZNF195               629
PIK3R1               724
C6orf118             469
STAB2               2551
BRCA1               1884
MGAT5B               801
MYL10                226
NUP153              1475
LZTR1                840
MTMR12               747
ZKSCAN1              563
COIL                 576
NBN                  754
ATG4C                458
RAB42                105

In [74]:
# add the Protein_length column to the relevant mutation dataset 
Hugo_symbols_relevant_SIGNIFICANT_genes_onlyTN_Q1.reset_index(level=0, inplace=True)
Hugo_symbols_relevant_SIGNIFICANT_genes_onlyTN_Q1.rename(columns={"index": "Hugo_Symbol"}, inplace=True)
Hugo_symbols_relevant_SIGNIFICANT_genes_onlyTN_Q1

   Hugo_Symbol  Protein_length
0         TP53             393
1       PIK3CA            1068
2        MAML3            1138
3         PTEN             403
4       NOTCH2            2471
5       CDKN2A             156
6        FBXW7             707
7          RB1             928
8       ZNF195             629
9       PIK3R1             724
10    C6orf118             469
11       STAB2            2551
12       BRCA1            1884
13      MGAT5B             801
14       MYL10             226
15      NUP153            1475
16       LZTR1             840
17      MTMR12             747
18     ZKSCAN1             563
19        COIL             576
20         NBN             754
21       ATG4C             458
22       RAB42             105

In [75]:
# add the protein lengths to the mutation dataset 
data_mutation_SINIFICANTgenes_onlyTN_q_1 = data_mutation_SINIFICANTgenes_onlyTN_q_1.join(Hugo_symbols_relevant_SIGNIFICANT_genes_onlyTN_Q1.set_index('Hugo_Symbol'), on='Hugo_Symbol')
data_mutation_SINIFICANTgenes_onlyTN_q_1

,PATIENT_ID,Tumor_Sample_Barcode,Hugo_Symbol,Chromosome,Start_Position,End_Position,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,...,HGVSc,HGVSp_Short,Transcript_ID,Gene_length,ENSP,Hugo_variant,Mutation_length,Protein_position_start,Protein_position_end,Protein_length
15,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,TP53,17,7574003.0,7574003.0,Nonsense_Mutation,SNP,G,G,...,ENST00000269305.4:c.1024C>T,p.R342*,ENST00000269305,25760,NaN,TP53_Nonsense_Mutation,1.0,342.0,342.0,393
18,brca_smc_2018_BB01_002,brca_smc_2018_BB01_002,PIK3CA,3,178952150.0,178952151.0,Frame_Shift_Ins,INS,-,-,...,ENST00000263967.3:c.3205_3206insTTTT,p.*1069Ffs*5,ENST00000263967,91980,NaN,PIK3CA_Frame_Shift_Ins,2.0,1069.0,1069.0,1068
22,brca_smc_2018_BB01_004,brca_smc_2018_BB01_004,TP53,17,7577117.0,7577117.0,Missense_Mutation,SNP,A,A,...,ENST00000269305.4:c.821T>G,p.V274G,ENST00000269305,25760,NaN,TP53_Missense_Mutation,1.0,274.0,274.0,393
25,brca_smc_2018_BB01_004,brca_smc_2018_BB01_004,MAML3,4,140811082.0,140811083.0,In_Frame_Ins,INS,-,-,...,ENST00000509479.2:c.1508_1509insCAA,p.Q503delinsHK,ENST00000509479,437432,NaN,MAML3_In_Frame_Ins,2.0,503.0,503.0,1138
34,brca_smc_2018_BB01_005,brca_smc_2018_BB01_005,PIK3CA,3,178952085.0,178952085.0,Missense_Mutation,SNP,A,A,...,ENST00000263967.3:c.3140A>G,p.H1047R,ENST00000263967,91980,NaN,PIK3CA_Missense_Mutation,1.0,1047.0,1047.0,1068
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138181,MBCProject_pyhbI1H5,MBC-MBCProject_pyhbI1H5-Tumor-SM-GQCX6,TP53,17,7579356.0,7579356.0,Missense_Mutation,SNP,G,G,...,ENST00000269305.4:c.331C>G,p.L111V,ENST00000269305,25760,NaN,TP53_Missense_Mutation,1.0,111.0,111.0,393
138413,MBCProject_rJHBiKTl,MBC-MBCProject_rJHBiKTl-Tumor-SM-DL3K3,TP53,17,7578271.0,7578271.0,Missense_Mutation,SNP,T,T,...,ENST00000269305.4:c.578A>G,p.H193R,ENST00000269305,25760,NaN,TP53_Missense_Mutation,1.0,193.0,193.0,393
138591,MBCProject_rYSXcxcV,RP-1156_MBCProject_rYSXcxcV_T1_v4_Exome,TP53,17,7578208.0,7578208.0,Missense_Mutation,SNP,T,T,...,ENST00000269305.4:c.641A>G,p.H214R,ENST00000269305,25760,NaN,TP53_Missense_Mutation,1.0,214.0,214.0,393
138717,MBCProject_rvULI3TV,MBC-MBCProject_rvULI3TV-Tumor-SM-DL41F,ZKSCAN1,7,99630937.0,99630938.0,Frame_Shift_Ins,INS,-,-,...,ENST00000324306.6:c.810dup,p.R271Qfs*3,ENST00000324306,26109,NaN,ZKSCAN1_Frame_Shift_Ins,2.0,270.0,270.0,563
138871,MBCProject_xBfJfri9,MBC-MBCProject_xBfJfri9-Tumor-SM-CGLAP,PTEN,10,89720799.0,89720802.0,Frame_Shift_Del,DEL,TACT,TACT,...,ENST00000371953.3:c.955_958del,p.T319*,ENST00000371953,108818,NaN,PTEN_Frame_Shift_Del,4.0,317.0,317.0,403

In [76]:
# save the dataset 
os.chdir("C:/Users/Cristina/OneDrive/Documenti/BCG/Tesi/MutClust_input_definitivo")
data_mutation_SINIFICANTgenes_onlyTN_q_1.to_csv("data_mutation_SINIFICANTgenes_ONLYhugo_onlyTN_Q1_definitivo.txt", index=False, sep='\t')

In [77]:
data_mutation_SINIFICANTgenes_onlyTN_q_1.Variant_Classification.nunique()

14

In [78]:
relevant_ONLYHugoSymbols_ProteinLength_onlyTN_Q1 = protein_length_only_Hugo_Symbol(data_mutation_SINIFICANTgenes_onlyTN_q_1)
relevant_ONLYHugoSymbols_ProteinLength_onlyTN_Q1

       symbol  length
0        TP53     393
1      PIK3CA    1068
3       MAML3    1138
8        PTEN     403
19     NOTCH2    2471
43     CDKN2A     156
59      FBXW7     707
64        RB1     928
75     ZNF195     629
78     PIK3R1     724
103  C6orf118     469
110     STAB2    2551
175     BRCA1    1884
183    MGAT5B     801
196     MYL10     226
213    NUP153    1475
246     LZTR1     840
262    MTMR12     747
265   ZKSCAN1     563
292      COIL     576
358       NBN     754
374     ATG4C     458
479     RAB42     105

In [79]:
len(relevant_ONLYHugoSymbols_ProteinLength_onlyTN_Q1)

23

In [80]:
relevant_ONLYHugoSymbols_ProteinLength_onlyTN_Q1.isna().sum()

symbol    0
length    0
dtype: int64

In [81]:
# save the dataset 
os.chdir("C:/Users/Cristina/OneDrive/Documenti/BCG/Tesi/MutClust_input_definitivo")
relevant_ONLYHugoSymbols_ProteinLength_onlyTN_Q1.to_csv("Symbol_ProteinLength_relevantONLYhugosymbols_onlyTN_Q1_definitivo.txt", index=False, sep='\t')